import type { Part1Topic } from "../schema";
import { fix, phrase, topic, vocab, q } from "../content-builders";

/** Core Part 1 topics with the full teaching payload: vocabulary, phrases,
 *  questions, idea seeds, patterns, Band 6 and 6.5 models and corrections. */
export const part1CoreTopics: Part1Topic[] = [
  topic({
    slug: "home",
    title: "Home",
    banglaTitle: "বাসা",
    summary: "The most common Part 1 opener. Learn to describe a home without listing 'big, beautiful, good'.",
    tags: ["part 1", "daily life", "core"],
    vocabulary: [
      vocab("flat / apartment", "noun", "ফ্ল্যাট", "We live in a small flat on the fourth floor."),
      vocab("spacious", "adjective", "প্রশস্ত", "My aunt’s house is quite spacious compared with ours."),
      vocab("cosy", "adjective", "আরামদায়ক ও ছোট", "Our living room is small but cosy."),
      vocab("within walking distance", "phrase", "হাঁটার দূরত্বে", "Everything I need is within walking distance."),
      vocab("get the morning sun", "phrase", "সকালের রোদ পাওয়া", "My room gets the morning sun, which I like."),
      vocab("move in", "verb", "ওঠা (নতুন বাসায়)", "We moved in about three years ago."),
    ],
    phrases: [
      phrase("I live in a modest flat", "আমি একটি সাধারণ ফ্ল্যাটে থাকি", "I live in a modest flat with my parents and my sister."),
      phrase("It’s not huge, but it’s practical", "বড় নয়, তবে কাজের", "It’s not huge, but it’s practical — it has everything we need."),
      phrase("The best thing about it is…", "সবচেয়ে ভালো দিক হলো…", "The best thing about it is the location — the bus stop is right outside."),
    ],
    questions: [
      q(
        "Do you live in a house or an apartment?",
        "আপনি বাড়িতে থাকেন নাকি ফ্ল্যাটে?",
        "Can you give a developed answer about your living situation?",
        ["Apartment / family house", "Who you live with", "One detail about the location", "One thing you would change"],
        ["I live in a ___ with ___. The best thing is ___ because ___.", "I live in a flat with my parents, and the best thing is the location — the market is five minutes away."],
        "I live in a flat with my family. It’s not very big, but the location is convenient. There’s a market and a bus stop nearby, so I don’t need to travel much.",
        "I live in a flat with my parents and my younger sister. It’s fairly small, but I like it because everything I need is within walking distance — the market, my college and even a park. If I could change one thing, I’d add a balcony.",
        [fix("I am living in a flat from three years.", "I have been living in a flat for three years.", "Use 'have been living' for something that continues, with 'for' + duration.")],
        ["a flat on the fourth floor", "a two-bedroom flat", "a family house"],
        ["Is your home a good place to study?", "Would you like to move to a different area?"],
      ),
      q(
        "What kind of home would you like to have in the future?",
        "ভবিষ্যতে কেমন বাসা চান?",
        "Can you use future forms naturally?",
        ["Type of home", "Where", "Why", "One detail (garden, view)"],
        ["I’d like to have ___ , probably in ___ , mainly because ___.", "I’d like to have a small house with a garden, probably outside the city, mainly because it’s quieter."],
        "In the future, I’d like to have a house with a small garden. I think it would be better than a flat because I’d have more space and it would be quieter.",
        "Eventually I’d like a modest house with a bit of outdoor space, probably on the edge of the city. I’d rather commute a little than live in a crowded area — and honestly, I’d like a place where my parents can stay comfortably too.",
        [fix("I will want a big house in future with garden.", "I’d like a house with a garden in the future.", "Use 'would like' for wishes; add articles: 'a garden'.")],
        ["a detached house", "a place with a garden", "a quiet neighbourhood"],
        ["Do you prefer living alone or with family?"],
      ),
    ],
  }),
  topic({
    slug: "hometown",
    title: "Hometown",
    banglaTitle: "নিজ শহর",
    summary: "A guaranteed topic. Learn to say where it is, what it is like and how it has changed — the third part is where the marks are.",
    tags: ["part 1", "places", "core"],
    vocabulary: [
      vocab("district town", "noun", "জেলা শহর", "My hometown is a small district town in the north."),
      vocab("quiet", "adjective", "শান্ত", "It’s very quiet compared with Dhaka."),
      vocab("close-knit", "adjective", "ঘনিষ্ঠ (সম্প্রদায়)", "People there are quite close-knit."),
      vocab("has changed a lot", "phrase", "অনেক বদলে গেছে", "It has changed a lot over the last ten years."),
      vocab("opportunities", "noun", "সুযোগ", "There aren’t many job opportunities there."),
      vocab("grow up", "verb", "বড় হওয়া", "I grew up there and moved to Dhaka for university."),
    ],
    phrases: [
      phrase("It’s a small town in the north", "উত্তরে একটি ছোট শহর", "It’s a small town in the north, about six hours from Dhaka."),
      phrase("What I like most is…", "সবচেয়ে বেশি ভালো লাগে…", "What I like most is how calm it feels."),
      phrase("It has changed beyond recognition", "অনেক বদলে গেছে", "The main road has changed beyond recognition in ten years."),
    ],
    questions: [
      q(
        "Where is your hometown?",
        "আপনার শহর কোথায়?",
        "Can you locate it and add one visual or factual detail?",
        ["Region", "Distance from big city", "What it’s known for", "Your connection to it"],
        ["It’s in ___ , about ___ from ___ , and it’s known for ___.", "It’s in the north, about six hours from Dhaka, and it’s known for its rice fields."],
        "My hometown is in the north of Bangladesh, not far from Rangpur. It’s a small town, and most people there work in farming or small businesses.",
        "My hometown is in the north, roughly six hours from Dhaka by bus. It’s a small district town — mostly farming, though a lot of young people have moved to the cities for work. I grew up there, so it still feels like home.",
        [fix("My hometown is situated in the north side of Bangladesh.", "My hometown is in the north of Bangladesh.", "Use 'in the north of', not 'north side of'.")],
        ["a district town", "a riverside town", "not far from the border"],
        ["What do people do for a living there?"],
      ),
      q(
        "How has your hometown changed in recent years?",
        "সাম্প্রতিক বছরগুলোতে শহর কীভাবে বদলেছে?",
        "Can you describe change using the present perfect and a comparison?",
        ["Infrastructure", "Buildings", "People moving away", "One thing that improved"],
        ["It has changed a lot — ___ , and now ___ .", "It has changed a lot — there are new roads and apartment buildings, and now you see far more traffic."],
        "My hometown has changed a lot. There are more buildings and roads now, and also more traffic. I think it’s more developed than before.",
        "It’s changed quite a bit, actually. Ten years ago there was one main road; now there are three, and a few apartment blocks have appeared. The main difference, though, is that lots of young people have moved away for work, so it feels quieter in a different way.",
        [fix("It is changing from last ten years.", "It has changed over the last ten years.", "Use present perfect for change up to now: 'has changed over'.")],
        ["new roads", "apartment blocks", "young people moving away"],
        ["Would you like to live there again in the future?"],
      ),
    ],
  }),
  topic({
    slug: "family",
    title: "Family",
    banglaTitle: "পরিবার",
    summary: "Introduce family members naturally: relationship, personality, and one habit — not a list of names and ages.",
    tags: ["part 1", "people", "core"],
    vocabulary: [
      vocab("eldest", "adjective", "সবার বড়", "My eldest cousin works in a bank."),
      vocab("extended family", "noun", "বড় পরিবার", "We have a fairly large extended family."),
      vocab("supportive", "adjective", "সহযোগী", "My parents are very supportive."),
      vocab("get on well with", "phrase", "ভালো সম্পর্ক থাকা", "I get on well with my sister."),
      vocab("look after", "verb", "দেখাশোনা করা", "My grandmother looks after my nephew."),
      vocab("spend time together", "phrase", "একসাথে সময় কাটানো", "We try to spend time together at weekends."),
    ],
    phrases: [
      phrase("I’m the eldest in my family", "আমি পরিবারের বড়", "I’m the eldest in my family, so I help my brother with his studies."),
      phrase("We’re a fairly close family", "আমরা বেশ ঘনিষ্ঠ পরিবার", "We’re a fairly close family — we eat together most evenings."),
      phrase("She’s the one who…", "তিনিই সেই মানুষ যিনি…", "He’s the one who always organises family gatherings."),
    ],
    questions: [
      q(
        "How many people are there in your family?",
        "আপনার পরিবারে কতজন?",
        "A number is not enough — the examiner wants a small picture of the household.",
        ["Number", "Who they are", "One relationship detail", "A habit you share"],
        ["There are ___ of us — ___. We usually ___.", "There are five of us — my parents, my grandparents and me. We usually have dinner together."],
        "There are five people in my family: my parents, my grandmother, my younger brother and me. We live in the same flat, and we usually eat dinner together.",
        "There are five of us — my parents, my grandmother, my younger brother and me. It’s a fairly close family; we have dinner together most evenings, and my grandmother talks about the old days, which I actually enjoy.",
        [fix("We are five members in my family.", "There are five of us in my family.", "Natural phrasing is 'there are five of us'.")],
        ["a close family", "we eat together", "my grandmother lives with us"],
        ["Do you spend a lot of time with your family?"],
      ),
      q(
        "Who are you closest to in your family?",
        "পরিবারে কার সাথে বেশি ঘনিষ্ঠ?",
        "Can you describe a relationship rather than just naming a person?",
        ["Who", "Why close", "What you do together", "One personality detail"],
        ["I’m closest to my ___ because ___. We ___.", "I’m closest to my sister because we’re nearly the same age, and we talk about everything."],
        "I’m closest to my sister. She’s two years younger than me, and we talk a lot. We usually watch dramas together in the evening.",
        "Probably my sister. She’s two years younger, so we grew up doing everything together — and even now we text each other about ten times a day. She’s the calm one in the family, which balances things out, because I tend to panic.",
        [fix("I am close with my sister.", "I’m close to my sister.", "Use 'close to' + person in this meaning.")],
        ["we’re nearly the same age", "she’s very patient", "we talk about everything"],
        ["Are you similar to your parents in personality?"],
      ),
    ],
  }),
  topic({
    slug: "friends",
    title: "Friends",
    banglaTitle: "বন্ধু",
    summary: "Talk about friendship as a habit, not a list: how you met, what you do together, why it lasts.",
    tags: ["part 1", "people", "core"],
    vocabulary: [
      vocab("best friend", "noun", "সেরা বন্ধু", "My best friend lives in the same building."),
      vocab("get to know", "verb", "জানা-শোনা হওয়া", "We got to know each other in school."),
      vocab("hang out", "verb", "সময় কাটানো", "We usually hang out at a tea stall nearby."),
      vocab("in touch", "phrase", "যোগাযোগ রাখা", "We keep in touch even though she moved."),
      vocab("reliable", "adjective", "নির্ভরযোগ্য", "He’s the most reliable person I know."),
      vocab("have a lot in common", "phrase", "ভাগাভাগি করে নেওয়ার মতো আগ্রহ থাকা", "We have a lot in common, especially music."),
    ],
    phrases: [
      phrase("We’ve known each other since…", "আমরা চেনা-জানা সেই থেকে…", "We’ve known each other since school."),
      phrase("We get on like a house on fire", "খুব ভালো মানিয়ে যায়", "We get on like a house on fire — we think the same way."),
      phrase("He’s easy to talk to", "তার সাথে কথা বলা সহজ", "She’s easy to talk to, which matters a lot to me."),
    ],
    questions: [
      q(
        "Do you have many friends?",
        "আপনার অনেক বন্ধু আছে?",
        "Can you distinguish close friends from a wider circle?",
        ["Number of close friends", "Wider circle", "Why few or many", "One habit"],
        ["I’d say I have ___ close friends, though I know ___ .", "I’d say I have two really close friends, though I know plenty of people from college."],
        "I have a few close friends, maybe three. I also know many classmates, but they are not very close friends. I prefer a small group.",
        "Not that many close ones — probably three, though I know quite a lot of people from university. I think that’s normal: you spend most of your energy on a couple of people you really trust, and the rest stay as friendly acquaintances.",
        [fix("I have many many friends but very much close is only two.", "I have quite a few friends, but only two are really close.", "Avoid stacked quantifiers; use 'quite a few' and a clear contrast.")],
        ["a small circle", "plenty of classmates", "close friends"],
        ["Is it easy to make friends in your area?"],
      ),
      q(
        "What do you usually do with your friends?",
        "বন্ধুদের সাথে সাধারণত কী করেন?",
        "Can you describe a routine activity with a reason and a detail?",
        ["Activity", "Where", "How often", "Why you enjoy it"],
        ["We usually ___ , maybe ___ times a ___, because ___.", "We usually meet for tea, maybe twice a week, because it’s cheap and we can talk for hours."],
        "I meet my friends at a tea stall near my house. We drink tea and talk about many things. Sometimes we play cricket at the weekend.",
        "We usually meet at a tea stall near my house — it’s cheap and nobody rushes you, so we end up talking for two or three hours. If the weather is good, we play cricket in the nearby field, though honestly we’re not very good at it.",
        [fix("We are doing chit-chat when we meet.", "We usually chat when we meet.", "chit-chat is a noun; use 'chat' as the verb.")],
        ["meet for tea", "play cricket", "talk for hours"],
        ["Do you prefer meeting friends at home or outside?"],
      ),
    ],
  }),
  topic({
    slug: "neighbours",
    title: "Neighbours",
    banglaTitle: "প্রতিবেশী",
    summary: "A frequent Part 1 topic that tests social vocabulary and comparison between areas.",
    tags: ["part 1", "people", "community"],
    vocabulary: [
      vocab("neighbourhood", "noun", "পাড়া", "My neighbourhood is quiet in the mornings."),
      vocab("friendly", "adjective", "বন্ধুত্বপূর্ণ", "Our neighbours are quite friendly."),
      vocab("help each other out", "phrase", "একে অন্যের সাহায্য করা", "We help each other out during Ramadan."),
      vocab("mind your own business", "phrase", "নিজের কাজে থাকা", "In big cities, people mostly mind their own business."),
      vocab("nearby", "adverb", "কাছাকাছি", "There’s a small shop nearby."),
      vocab("get on with", "phrase", "মিলেমিশে থাকা", "We get on well with the family next door."),
    ],
    phrases: [
      phrase("We get on well with them", "আমরা তাদের সাথে ভালো সম্পর্ক রাখি", "We get on well with them — they’re helpful."),
      phrase("People keep to themselves", "মানুষ নিজেদের মধ্যে থাকে", "In Dhaka, people mostly keep to themselves."),
      phrase("It’s a friendly area", "এলাকাটা বন্ধুত্বপূর্ণ", "It’s a friendly area, especially during festivals."),
    ],
    questions: [
      q(
        "Do you know your neighbours well?",
        "প্রতিবেশীদের ভালোভাবে চেনেন?",
        "Relationship + a specific detail or event.",
        ["Which neighbours", "How you know them", "One shared activity", "Difference from the past"],
        ["I know ___ quite well — we ___ , although ___.", "I know the family next door quite well — we exchange food during festivals, although the rest of the building keeps to themselves."],
        "Yes, I know some of them. We say hello and sometimes we share food. In my building, most people are friendly.",
        "Fairly well, actually — particularly the family next door. We exchange food during Eid, and their son sometimes asks me for help with English. Beyond that, the building is quite private, which suits me fine.",
        [fix("My neighbours are very much helpful.", "My neighbours are very helpful.", "Avoid 'very much' before adjectives; use 'really'/'very'.")],
        ["exchange food", "help with schoolwork", "say hello"],
        ["Do neighbours help each other where you live?"],
      ),
    ],
  }),
  topic({
    slug: "studies",
    title: "Studies",
    banglaTitle: "পড়াশোনা",
    summary: "Almost guaranteed to appear. Learn to say what you study, why, and what makes it hard — with the right prepositions.",
    tags: ["part 1", "education", "core"],
    vocabulary: [
      vocab("major in", "phrase", "মেজর করা", "I’m majoring in accounting."),
      vocab("coursework", "noun", "কোর্সের কাজ", "The coursework keeps me busy most weeks."),
      vocab("deadline", "noun", "সময়সীমা", "We had three deadlines in one week."),
      vocab("take notes", "verb", "নোট নেওয়া", "I take notes in class and revise at home."),
      vocab("keep up with", "phrase", "সাথে তাল মিলিয়ে চলা", "It’s hard to keep up with the syllabus."),
      vocab("revision", "noun", "পুনরালোচনা", "I do my revision in the morning."),
    ],
    phrases: [
      phrase("I’m studying … at … university", "আমি … বিশ্ববিদ্যালয়ে … পড়ছি", "I’m studying business at Dhaka University."),
      phrase("What I find hardest is…", "সবচেয়ে কঠিন লাগে…", "What I find hardest is the statistics part."),
      phrase("It’s demanding, but I enjoy it", "কঠিন, তবে ভালো লাগে", "It’s demanding, but I enjoy it, especially the practical side."),
    ],
    questions: [
      q(
        "What are you studying?",
        "আপনি কী পড়ছেন?",
        "Subject + where + one honest reaction.",
        ["Subject", "Institution", "Why you chose it", "What you find hard or enjoy"],
        ["I’m studying ___ at ___. I chose it because ___.", "I’m studying accounting at a private university. I chose it because I’m good with numbers."],
        "I’m studying accounting at a private university in Dhaka. I chose it because I want to work in a bank. The exams are quite hard, but I like the subject.",
        "I’m studying accounting at a private university in Dhaka — mainly because I’ve always been comfortable with numbers, and it leads to decent jobs. What I find hardest is the statistics side; the practical accounting papers are much easier for me.",
        [fix("I am studying in accounting in Dhaka University.", "I’m studying accounting at Dhaka University.", "No 'in' before a subject; use 'at' for institutions.")],
        ["business studies", "computer science", "accounting"],
        ["Why did you choose that subject?"],
      ),
      q(
        "Do you prefer studying alone or with others?",
        "একা পড়তে ভালো লাগে নাকি অন্যদের সাথে?",
        "A preference question — you must compare and justify.",
        ["Preference", "Reason", "When the other is better", "One detail"],
        ["I prefer ___ because ___, although ___ .", "I prefer studying alone because I get distracted easily, although group revision helps before exams."],
        "I prefer studying alone. I can concentrate better when it’s quiet. But sometimes I study with my friends before exams, and that is helpful.",
        "On the whole, alone — I get distracted very easily, so a quiet room works better. That said, I do join a small group before exams, because explaining something to someone else shows me what I haven’t really understood yet.",
        [fix("I am preferring studying alone.", "I prefer studying alone.", "'prefer' is a state verb — not used in continuous form.")],
        ["study alone", "group revision", "quiet room"],
        ["What time of day do you study best?"],
      ),
    ],
  }),
  topic({
    slug: "work",
    title: "Work",
    banglaTitle: "কাজ",
    summary: "Whether you work or study, expect this topic. Talk about tasks, colleagues and the part you actually enjoy.",
    tags: ["part 1", "work", "core"],
    vocabulary: [
      vocab("part-time", "adjective", "খণ্ডকালীন", "I do a part-time job at a bookshop."),
      vocab("tutor", "noun", "শিক্ষক (ব্যক্তিগত)", "I work as a tutor in the evenings."),
      vocab("shift", "noun", "শিফট", "My shift usually starts at four."),
      vocab("responsibility", "noun", "দায়িত্ব", "My main responsibility is looking after the shop."),
      vocab("learn on the job", "phrase", "কাজ করতে করতে শেখা", "I’ve learned most of it on the job."),
      vocab("career prospects", "noun", "কর্মজীবনের সম্ভাবনা", "The career prospects in this field are decent."),
    ],
    phrases: [
      phrase("I work as a…", "আমি … হিসেবে কাজ করি", "I work as a tutor for school students."),
      phrase("My day is fairly structured", "আমার দিন একটি নির্দিষ্ট ছকে চলে", "My day is fairly structured once classes end."),
      phrase("What I like about it is…", "এর মধ্যে যা ভালো লাগে…", "What I like about it is the people I meet."),
    ],
    questions: [
      q(
        "Do you work or are you a student?",
        "আপনি কাজ করেন নাকি ছাত্র?",
        "The classic opener — extend beyond one word.",
        ["Status", "What exactly you do", "How long", "One detail about the routine"],
        ["I’m a ___ , and I ___ . I’ve been doing it for ___.", "I’m a student, and I also work part-time in a bookshop. I’ve been doing it for about a year."],
        "I’m a student. I also work part-time in a bookshop near my university. I’ve been doing that for about a year, mostly at weekends.",
        "I’m a full-time student, but I also work part-time at a bookshop near my university — mostly weekends, about fifteen hours a week. I’ve been doing it for about a year, and it’s taught me more about dealing with people than any class has.",
        [fix("I am doing job in a shop.", "I work in a shop.", "Use 'work' as the verb; 'job' is a noun.")],
        ["part-time job", "weekend shifts", "a bookshop"],
        ["Why did you choose that job?"],
      ),
      q(
        "What do you like most about your work or studies?",
        "কাজ বা পড়াশোনার কোন দিকটি সবচেয়ে ভালো লাগে?",
        "A preference question: pick one thing and develop it.",
        ["The best part", "Why", "A small example", "A drawback"],
        ["The best part is ___ , mainly because ___.", "The best part is the people I meet, mainly because every customer has a different story."],
        "I like the people I meet at the shop. Some customers come every week, so I know them now. It makes the work interesting.",
        "Honestly, it’s the people. Because it’s a small shop, I see the same customers every week, and a few of them now stop just to chat. The downside is the hours — I sometimes finish late and then have to study, which is exhausting.",
        [fix("I like most the people.", "I like the people most. / What I like most is the people.", "Word order: 'most' does not go before the noun in this pattern.")],
        ["meeting people", "the same regular customers", "flexible hours"],
        ["Would you like to do this job permanently?"],
      ),
    ],
  }),
  topic({
    slug: "school",
    title: "School",
    banglaTitle: "স্কুল জীবন",
    summary: "Past-tense territory: your school days, teachers, subjects and one vivid memory.",
    tags: ["part 1", "education", "past"],
    vocabulary: [
      vocab("primary school", "noun", "প্রাথমিক বিদ্যালয়", "I went to a primary school near my house."),
      vocab("strict", "adjective", "কঠোর", "Our maths teacher was quite strict."),
      vocab("memorise", "verb", "মুখস্থ করা", "We used to memorise a lot for exams."),
      vocab("extracurricular", "adjective", "পাঠ্যক্রমের বাইরের", "I took part in extracurricular activities."),
      vocab("classmate", "noun", "সহপাঠী", "I still meet a few old classmates."),
      vocab("look forward to", "phrase", "অধীর আগ্রহে অপেক্ষা করা", "I used to look forward to the games period."),
    ],
    phrases: [
      phrase("I went to school in…", "আমি স্কুলে পড়েছি …", "I went to school in my hometown."),
      phrase("What I remember most is…", "সবচেয়ে বেশি মনে আছে…", "What I remember most is the annual sports day."),
      phrase("We had to…", "আমাদের করতে হতো…", "We had to wear a uniform every day."),
    ],
    questions: [
      q(
        "Did you like your school?",
        "স্কুল ভালো লাগত?",
        "A past-tense opinion question — general view plus one memory.",
        ["Yes/no with strength", "What you liked", "One memory", "What you disliked"],
        ["I did, mostly — I really enjoyed ___ , although ___.", "I did, mostly. I really enjoyed the sports and art classes, although the exams were stressful."],
        "Yes, I liked my school. The teachers were friendly and I had many friends. But the exams were very stressful, so I didn’t like that part.",
        "I did, on the whole. There were things I complained about at the time — the uniform, the homework — but looking back, the teachers were genuinely supportive, and the sports days were the highlight of the year. I still keep in touch with a couple of classmates from then.",
        [fix("I was liking my school very much.", "I liked my school a lot.", "'like' is not used in continuous form; use 'a lot' rather than 'very much' at the end.")],
        ["annual sports day", "friendly teachers", "strict rules"],
        ["What was your favourite subject at school?"],
      ),
    ],
  }),
  topic({
    slug: "daily-routine",
    title: "Daily routine",
    banglaTitle: "দিনলিপি",
    summary: "The topic where present simple, frequency adverbs and sequencing all appear at once.",
    tags: ["part 1", "routine", "core"],
    vocabulary: [
      vocab("wake up", "verb", "ঘুম থেকে ওঠা", "I usually wake up around seven."),
      vocab("get ready", "phrase", "প্রস্তুত হওয়া", "It takes me twenty minutes to get ready."),
      vocab("commute", "verb", "যাওয়া-আসা করা (নিয়মিত)", "I commute to university by bus."),
      vocab("fit in", "phrase", "সময় বের করা", "I try to fit in some exercise."),
      vocab("unwind", "verb", "মন হালকা করা", "I unwind by watching something light."),
      vocab("stick to a routine", "phrase", "রুটিন মেনে চলা", "I try to stick to a routine, but it varies."),
    ],
    phrases: [
      phrase("My day starts at…", "আমার দিন শুরু হয়…", "My day starts at about seven."),
      phrase("After that, I…", "এরপর আমি…", "After that, I head to university."),
      phrase("By evening, I’m usually…", "সন্ধ্যা নাগাদ আমি সাধারণত…", "By evening, I’m usually quite tired."),
    ],
    questions: [
      q(
        "What is your daily routine like?",
        "আপনার দৈনন্দিন রুটিন কেমন?",
        "Can you sequence four or five actions in present simple?",
        ["Morning", "Afternoon", "Evening", "One fixed habit"],
        ["I usually ___ , then ___ , and in the evening ___ .", "I usually wake up at seven, then I go to classes, and in the evening I study for a couple of hours."],
        "I wake up at seven and have breakfast. Then I go to university in the morning. In the evening I study and watch something on my phone.",
        "I’m up around seven, and I usually have breakfast while checking messages — not a great habit, I know. Classes run from nine until about two, then I come home and rest for an hour. Evenings are for studying, and I try to fit in a walk before dinner.",
        [fix("I am waking up at six and then I am taking a bath.", "I wake up at six and then I take a shower.", "Habits use present simple; 'take a bath' is fine but 'have a shower' is more common in speech.")],
        ["have breakfast", "go to classes", "study in the evening"],
        ["Is your routine the same at weekends?"],
      ),
    ],
  }),
  topic({
    slug: "mornings",
    title: "Morning routines",
    banglaTitle: "সকালের রুটিন",
    summary: "A narrow topic that rewards detail — smells, sounds, light, and how your morning sets up the day.",
    tags: ["part 1", "routine", "detail"],
    vocabulary: [
      vocab("early riser", "noun", "সকালে ওঠা মানুষ", "I’m not a natural early riser."),
      vocab("fresh", "adjective", "সতেজ", "I feel fresher in the morning."),
      vocab("rush", "verb", "দ্রুত করা", "I don’t like rushing in the morning."),
      vocab("alarm", "noun", "অ্যালার্ম", "My alarm goes off at six thirty."),
      vocab("productive", "adjective", "উৎপাদনশীল", "I’m most productive before breakfast."),
      vocab("slow start", "phrase", "ধীর শুরু", "I like a slow start with tea."),
    ],
    phrases: [
      phrase("I’m not a morning person", "আমি সকালের মানুষ নই", "I’m not a morning person, honestly."),
      phrase("Once I’m up, I’m fine", "একবার উঠে গেলে ঠিক থাকি", "Once I’m up, I’m fine — it’s the first ten minutes that are hard."),
      phrase("The first thing I do is…", "প্রথমেই যা করি…", "The first thing I do is make tea."),
    ],
    questions: [
      q(
        "What do you usually do in the morning?",
        "সকালে সাধারণত কী করেন?",
        "Detailed sequencing; a good place to show natural adverbs.",
        ["Wake-up time", "First action", "Breakfast", "Departure"],
        ["I normally wake up at ___ , and the first thing I do is ___ .", "I normally wake up around seven, and the first thing I do is make tea."],
        "In the morning, I wake up at seven and brush my teeth. Then I have breakfast with my family. After that I leave for university at eight thirty.",
        "I normally wake up around seven — though on some days the alarm wins and I sleep another ten minutes. First thing, I make tea, mostly because it forces me to get out of bed. Breakfast with my family is quick; I usually leave the house by half past eight.",
        [fix("In morning I am having breakfast.", "In the morning I have breakfast.", "Needs 'the', and habits use present simple.")],
        ["make tea", "have breakfast with family", "leave at eight thirty"],
        ["Are you a morning person?"],
      ),
    ],
  }),
  topic({
    slug: "evenings",
    title: "Evenings",
    banglaTitle: "সন্ধ্যা",
    summary: "Contrast evening habits with daytime habits, and use 'unwind', 'wind down' and 'by then'.",
    tags: ["part 1", "routine", "detail"],
    vocabulary: [
      vocab("wind down", "verb", "ধীরে ধীরে শান্ত হওয়া", "I wind down by reading."),
      vocab("catch up on", "phrase", "পিছিয়ে পড়া কাজ শেষ করা", "I catch up on messages in the evening."),
      vocab("quality time", "noun", "পরিবারের সাথে ভালো সময়", "Evenings are our quality time."),
      vocab("takeaway", "noun", "বাইরের খাবার", "Sometimes we order a takeaway."),
      vocab("late night", "phrase", "রাত জাগা", "I try to avoid late nights during exams."),
      vocab("quiet", "adjective", "শান্ত", "The evenings here are quiet."),
    ],
    phrases: [
      phrase("By evening I’m usually…", "সন্ধ্যায় আমি সাধারণত…", "By evening I’m usually done with classes."),
      phrase("I like to wind down with…", "…দিয়ে মন হালকা করি", "I like to wind down with a film."),
      phrase("Evenings are for…", "সন্ধ্যা হলো …-এর জন্য", "Evenings are for family, not for study."),
    ],
    questions: [
      q(
        "What do you usually do in the evening?",
        "সন্ধ্যায় সাধারণত কী করেন?",
        "Habit + reason + a contrast with the daytime.",
        ["Activity", "Who with", "Why then", "Difference from daytime"],
        ["In the evening I usually ___ , because ___.", "In the evening I usually watch a film with my family, because that’s when everyone is free."],
        "In the evening, I study for two hours. After that I watch TV with my family. Then I go to bed around eleven.",
        "Evenings are quite relaxed for me. I study for an hour or two, and after that the family sits together — we usually watch something while having dinner. It’s the only time everyone’s in the same room, so it matters more than it sounds.",
        [fix("In the evening I am watching TV and studying.", "In the evening I watch TV and study.", "Habits: present simple, not continuous.")],
        ["watch something with family", "study for two hours", "wind down"],
        ["Do you prefer the morning or the evening?"],
      ),
    ],
  }),
  topic({
    slug: "sleep",
    title: "Sleep",
    banglaTitle: "ঘুম",
    summary: "Sleep habits, naps and why sleep matters — a topic full of easy natural collocations.",
    tags: ["part 1", "health", "routine"],
    vocabulary: [
      vocab("stay up late", "phrase", "রাত জাগা", "I try not to stay up late before exams."),
      vocab("fall asleep", "verb", "ঘুমিয়ে পড়া", "I usually fall asleep within ten minutes."),
      vocab("nap", "noun", "ছোট ঘুম", "A short nap helps me concentrate."),
      vocab("sleepy", "adjective", "ঘুমঘুম", "I get sleepy after lunch."),
      vocab("well-rested", "adjective", "ভালো বিশ্রাম নেওয়া", "I feel well-rested after eight hours."),
      vocab("switch off", "phrase", "মন বন্ধ করা", "I switch off my phone before bed."),
    ],
    phrases: [
      phrase("I need about … hours of sleep", "আমার প্রায় … ঘণ্টা ঘুম দরকার", "I need about seven hours of sleep."),
      phrase("I try to avoid screens before bed", "ঘুমের আগে স্ক্রিন এড়াতে চেষ্টা করি", "I try to avoid screens before bed, though not always successfully."),
      phrase("A good night’s sleep changes everything", "ভালো ঘুম সব বদলে দেয়", "A good night’s sleep changes everything the next day."),
    ],
    questions: [
      q(
        "How many hours do you sleep at night?",
        "রাতে কত ঘণ্টা ঘুমান?",
        "A number plus a habit and a consequence.",
        ["Hours", "Sleep time", "Quality", "Effect the next day"],
        ["I usually get about ___ hours — I go to bed around ___ .", "I usually get about seven hours — I go to bed around eleven and wake at six."],
        "I sleep about seven hours. I go to bed at eleven and get up at six in the morning. Usually I sleep well.",
        "About seven, sometimes six if I have an assignment. I try to be in bed by eleven, though my phone often keeps me up a bit longer. If I get less than six, I notice it the next day — I’m slower in class and I can’t concentrate.",
        [fix("I am sleeping seven hours daily.", "I sleep about seven hours a day.", "Habit = present simple; 'daily' sounds formal here, 'a day' is natural.")],
        ["seven hours", "in bed by eleven", "feel sleepy after lunch"],
        ["Do you sleep more at weekends?"],
      ),
    ],
  }),
  topic({
    slug: "weekends",
    title: "Weekends",
    banglaTitle: "সাপ্তাহিক ছুটি",
    summary: "Compare weekend and weekday routines — perfect for contrast structures.",
    tags: ["part 1", "routine", "core"],
    vocabulary: [
      vocab("day off", "noun", "ছুটি", "Friday is my only day off."),
      vocab("relaxed", "adjective", "আরামে", "Weekends are more relaxed for me."),
      vocab("catch up on sleep", "phrase", "ঘুম পূরণ করা", "I catch up on sleep at weekends."),
      vocab("out and about", "phrase", "বাইরে চলাফেরা করা", "I like being out and about on Saturdays."),
      vocab("household chores", "noun", "ঘরের কাজ", "I help with household chores."),
      vocab("look forward to", "phrase", "অপেক্ষা করা", "I look forward to Fridays all week."),
    ],
    phrases: [
      phrase("At the weekend, I usually…", "সাপ্তাহিক ছুটিতে সাধারণত…", "At the weekend, I usually visit my grandparents."),
      phrase("Unlike weekdays, I…", "সপ্তাহের অন্য দিনের তুলনায়…", "Unlike weekdays, I don’t set an alarm."),
      phrase("It’s my chance to…", "এটা আমার সুযোগ…", "It’s my chance to switch off completely."),
    ],
    questions: [
      q(
        "What do you usually do at the weekend?",
        "সাপ্তাহিক ছুটিতে সাধারণত কী করেন?",
        "Routine + comparison with weekdays + one specific activity.",
        ["Main activity", "Who with", "Why", "How it differs"],
        ["At the weekend I usually ___ , which is different from weekdays because ___ .", "At the weekend I usually visit my cousins, which is different from my normal routine of studying all day."],
        "At the weekend, I usually sleep a little longer and then help my mother at home. In the afternoon, I meet my friends. On Friday, we sometimes go to the market.",
        "My weekends are much slower. I sleep in a bit, then help my mother with chores — she appreciates it, and honestly I don’t mind. Saturday afternoons I usually meet friends, and Friday evenings we go to my grandmother’s place for dinner, which has been a family habit for years.",
        [fix("In weekend I go to my village.", "At the weekend I go to my village.", "Use 'at the weekend'; 'in' is used for months and years.")],
        ["visit grandparents", "help with chores", "meet friends"],
        ["Do you prefer weekends or weekdays?"],
      ),
    ],
  }),
  topic({
    slug: "free-time",
    title: "Free time",
    banglaTitle: "অবসর সময়",
    summary:
      "The topic that reveals your vocabulary range most quickly — and where 'I do many things' fails.",
    tags: ["part 1", "leisure", "core"],
    vocabulary: [
      vocab("spare time", "noun", "অবসর সময়", "In my spare time I read or cycle."),
      vocab("pastime", "noun", "সময় কাটানোর কাজ", "Photography is my main pastime."),
      vocab("unwind", "verb", "মন হালকা করা", "I unwind by watching old films."),
      vocab("take up", "phrase", "শুরু করা (শখ)", "I took up cycling last year."),
      vocab("something productive", "phrase", "কিছু কাজের", "I try to do something productive."),
      vocab("hooked on", "phrase", "আসক্ত", "I’m hooked on that podcast."),
    ],
    phrases: [
      phrase("With whatever time I have, I…", "যতটুকু সময় পাই, তাতে…", "With whatever time I have, I usually read."),
      phrase("It’s how I switch off", "এভাবেই মন হালকা হয়", "Reading is how I switch off after class."),
      phrase("I’ve been doing it since…", "আমি এটি করছি … থেকে", "I’ve been doing it since school."),
    ],
    questions: [
      q(
        "What do you do in your free time?",
        "অবসর সময়ে কী করেন?",
        "Two activities, one reason, one detail — not a list.",
        ["Two activities", "Which one is regular", "Why you like it", "When you do it"],
        ["In my free time I usually ___ , and if I have longer I ___ .", "In my free time I usually read, and if I have longer I go cycling around my area."],
        "In my free time I listen to music and read books. I like music very much. Sometimes I also play cricket with my friends.",
        "Honestly, my free time is limited, so I keep it simple — reading, mostly fiction, and cycling if the weather allows. Reading is how I switch off; I usually get through a book every two or three weeks, mostly late at night when the house is quiet.",
        [fix("In free time I am doing many things.", "In my free time I do quite a few things.", "Add the article: 'in my free time'.")],
        ["reading fiction", "cycling in the evening", "listening to podcasts"],
        ["Do you think you have enough free time?"],
      ),
    ],
  }),
  topic({
    slug: "food",
    title: "Food",
    banglaTitle: "খাবার",
    summary: "Favourite dishes, home cooking and eating out — with natural collocations instead of 'very tasty'.",
    tags: ["part 1", "food", "core"],
    vocabulary: [
      vocab("home-cooked", "adjective", "ঘরে রান্না করা", "I prefer home-cooked food."),
      vocab("spicy", "adjective", "ঝাল", "The curry was slightly too spicy for me."),
      vocab("hearty", "adjective", "ভরপেট", "It was a hearty breakfast."),
      vocab("street food", "noun", "রাস্তার খাবার", "Dhaka has excellent street food."),
      vocab("eat out", "phrasal verb", "বাইরে খাওয়া", "We eat out maybe once a month."),
      vocab("a balanced diet", "noun", "সুষম খাদ্য", "I try to keep a balanced diet."),
    ],
    phrases: [
      phrase("My favourite dish is…", "আমার প্রিয় খাবার…", "My favourite dish is biryani — I only have it on special occasions."),
      phrase("I’m not fussy about food", "আমি খাবারে বাছবিচার করি না", "I’m not fussy about food, but I avoid very oily things."),
      phrase("We normally eat together", "আমরা সাধারণত একসাথে খাই", "We normally eat together in the evening."),
    ],
    questions: [
      q(
        "What is your favourite food?",
        "আপনার প্রিয় খাবার কী?",
        "Name it, say when you eat it, and why — avoid a one-line answer.",
        ["Dish", "When you eat it", "Why you like it", "Who cooks it"],
        ["My favourite is ___ , and I usually have it ___ because ___ .", "My favourite is biryani, and I usually have it at family gatherings because my aunt makes it properly."],
        "My favourite food is biryani. I eat it on special days like Eid. It is very tasty and I like the smell also.",
        "Biryani, without question — though it’s a once-in-a-while thing, usually on Eid or at weddings, because it takes hours to cook properly. My aunt makes it the traditional way, and honestly nothing from a restaurant comes close.",
        [fix("I like biryani very much, it is so much tasty.", "I like biryani a lot — it’s really tasty.", "Avoid 'so much' before adjectives and do not join two sentences with a comma.")],
        ["traditional biryani", "on special occasions", "a bit too spicy"],
        ["Do you prefer eating at home or outside?"],
      ),
      q(
        "Do you enjoy cooking?",
        "রান্না করতে ভালো লাগে?",
        "A yes/no question — use the three-step formula.",
        ["Answer", "Why / why not", "One dish you can make", "How often"],
        ["Yes, I do / Not really — I ___ because ___ .", "Yes, I do — I cook simple things because it’s cheaper than eating out."],
        "Yes, I enjoy cooking a little. I can cook rice, dal and egg curry. I usually cook at weekends when I have time.",
        "I do, though only simple things — rice, dal, and a decent egg curry. Mostly it’s a practical thing: cooking at home is far cheaper, and I know exactly what’s in it. Weekends are when I actually enjoy it rather than just doing it.",
        [fix("I am knowing how to cook some items.", "I know how to cook a few things.", "'know' is a state verb; 'items' is unnatural for food.")],
        ["simple dishes", "cook at weekends", "cheaper than eating out"],
        ["Who usually cooks in your family?"],
      ),
    ],
  }),
  topic({
    slug: "cooking",
    title: "Cooking",
    banglaTitle: "রান্না",
    summary: "Go beyond 'I can cook rice'. Learn method language, ingredients and how you learned.",
    tags: ["part 1", "food", "skills"],
    vocabulary: [
      vocab("recipe", "noun", "রেসিপি", "I got the recipe from my mother."),
      vocab("ingredients", "noun", "উপকরণ", "The ingredients are simple — onion, garlic and spices."),
      vocab("chop", "verb", "কাটা", "I usually chop the vegetables first."),
      vocab("boil", "verb", "সিদ্ধ করা", "Boil the rice for about fifteen minutes."),
      vocab("follow a recipe", "phrase", "রেসিপি অনুসরণ করা", "I follow a recipe the first time and then improvise."),
      vocab("trial and error", "phrase", "বারবার চেষ্টা করে শেখা", "I learned by trial and error."),
    ],
    phrases: [
      phrase("I learned from my mother", "মায়ের কাছে শিখেছি", "I learned the basics from my mother."),
      phrase("It’s not complicated — you just…", "কঠিন নয়, শুধু…", "It’s not complicated — you just fry the onions first."),
      phrase("I’m better at… than…", "আমি …-এ …-এর চেয়ে ভালো", "I’m better at cooking rice than curries."),
    ],
    questions: [
      q(
        "Do you know how to cook?",
        "রান্না করতে জানেন?",
        "A skill question — method and level matter more than a yes/no.",
        ["Skill level", "What you can cook", "How you learned", "One thing you can’t do"],
        ["I can cook ___ , and I learned mostly by ___ .", "I can cook simple things, and I learned mostly by watching my mother."],
        "Yes, I can cook. I learned from my mother when I was in school. I can cook rice, dal and chicken curry, but I cannot cook biryani.",
        "I can cook — basic cooking, anyway. Rice, dal, a few curries; I learned by standing in the kitchen with my mother and asking endless questions. What I can’t do is anything with fish, mostly because I can’t clean it properly.",
        [fix("I am knowing cooking.", "I know how to cook.", "'know how to + verb' is the natural pattern.")],
        ["learned from my mother", "simple everyday dishes", "can’t cook fish"],
        ["Do you think cooking is an important skill?"],
      ),
    ],
  }),
  topic({
    slug: "weather",
    title: "Weather",
    banglaTitle: "আবহাওয়া",
    summary: "Small talk with real vocabulary — heat, monsoon, humidity and how weather changes your plans.",
    tags: ["part 1", "nature", "core"],
    vocabulary: [
      vocab("humid", "adjective", "আর্দ্র", "Dhaka is extremely humid in summer."),
      vocab("chilly", "adjective", "ঠান্ডা (হালকা)", "Winter mornings can be chilly here."),
      vocab("pouring", "adjective", "ভীষণ বৃষ্টি", "It was pouring, so we stayed in."),
      vocab("forecast", "noun", "আবহাওয়ার পূর্বাভাস", "The forecast says rain all week."),
      vocab("unbearable", "adjective", "সহ্য করার মতো নয়", "The heat in May is almost unbearable."),
      vocab("mild", "adjective", "মৃদু", "Winter here is fairly mild."),
    ],
    phrases: [
      phrase("It’s been unusually hot", "অস্বাভাবিক গরম", "It’s been unusually hot for this time of year."),
      phrase("The weather affects everything", "আবহাওয়া সবকিছু প্রভাবিত করে", "The weather affects everything — traffic, mood, even what I eat."),
      phrase("I don’t mind the rain", "বৃষ্টি নিয়ে আমার সমস্যা নেই", "I don’t mind the rain as long as I’m not travelling."),
    ],
    questions: [
      q(
        "What is the weather like in your country?",
        "আপনার দেশে আবহাওয়া কেমন?",
        "Seasons + one effect on daily life.",
        ["Three seasons", "Extremes", "What you like", "How it affects your day"],
        ["We have ___ , and honestly ___ .", "We have three clear seasons, and honestly the summer heat is the hardest part."],
        "In my country, there are three main seasons. Summer is very hot, and the rainy season is wet. Winter is cool and comfortable. I like winter because the weather is nice.",
        "We get three main seasons — a hot summer, a wet monsoon, and a mild winter. The summer is the toughest: it’s so humid that even sitting still feels tiring, and the electricity cuts make it worse. Winter, on the other hand, is genuinely pleasant — cool mornings and no sweating.",
        [fix("Weather is very hot today.", "It’s very hot today. / The weather is hot today.", "Use 'it' for weather in the fixed expression 'it is hot'.")],
        ["hot and humid", "monsoon rain", "mild winter"],
        ["Does the weather affect what you do?"],
      ),
    ],
  }),
  topic({
    slug: "seasons",
    title: "Seasons",
    banglaTitle: "ঋতু",
    summary: "Compare seasons and explain a preference — comparison structures appear automatically here.",
    tags: ["part 1", "nature"],
    vocabulary: [
      vocab("monsoon", "noun", "বর্ষা", "The monsoon lasts from June to September."),
      vocab("seasonal fruit", "noun", "মৌসুমি ফল", "Mangoes are my favourite seasonal fruit."),
      vocab("harvest", "noun", "ফসল তোলা", "The harvest festival is in spring."),
      vocab("in full bloom", "phrase", "ফুলে ভরে ওঠা", "The trees are in full bloom in spring."),
      vocab("productivity", "noun", "উৎপাদনশীলতা", "My productivity drops in summer."),
      vocab("preferable", "adjective", "বাঞ্ছনীয়", "Cool weather is preferable for studying."),
    ],
    phrases: [
      phrase("My favourite season is…", "আমার প্রিয় ঋতু…", "My favourite season is winter."),
      phrase("It’s the best time for…", "এটি …-এর জন্য সবচেয়ে ভালো সময়", "Winter is the best time for travelling."),
      phrase("Compared with summer, …", "গ্রীষ্মের তুলনায়…", "Compared with summer, winter is much easier to work in."),
    ],
    questions: [
      q(
        "Which season do you like best?",
        "কোন ঋতু সবচেয়ে পছন্দ?",
        "Preference + reason + comparison.",
        ["Season", "Why", "What you do then", "Comparison"],
        ["I like ___ best, mainly because ___ , unlike ___ .", "I like winter best, mainly because it’s comfortable, unlike summer which drains me."],
        "I like winter best. The weather is cool and I can sleep well. In winter, we also have many festivals and I can eat different vegetables.",
        "Winter, definitely. It’s the only season when I can study for hours without feeling drained — and there’s a lot going on: weddings, picnics, and my cousin’s birthday. Summer is the opposite: I feel sluggish and my productivity drops noticeably.",
        [fix("I am liking winter season very much.", "I like winter a lot.", "'like' in simple present; 'winter season' is redundant.")],
        ["mild winter", "better concentration", "wedding season"],
        ["Has the weather changed compared with the past?"],
      ),
    ],
  }),
  topic({
    slug: "flowers",
    title: "Flowers",
    banglaTitle: "ফুল",
    summary: "A surprisingly common topic — learn names, purposes and one personal association.",
    tags: ["part 1", "nature", "detail"],
    vocabulary: [
      vocab("bouquet", "noun", "ফুলের তোড়া", "I bought a small bouquet for my aunt."),
      vocab("fragrant", "adjective", "সুবাসিত", "The garden was fragrant in the morning."),
      vocab("blossom", "noun", "মুকুল/ফুল ফোটা", "The trees were full of blossom."),
      vocab("decorate", "verb", "সাজানো", "We decorate the room with flowers."),
      vocab("seasonal", "adjective", "মৌসুমি", "Marigolds are seasonal and cheap in winter."),
      vocab("symbolise", "verb", "প্রতীকী হওয়া", "In our culture, flowers symbolise respect."),
    ],
    phrases: [
      phrase("I don’t know much about flowers, but…", "ফুল সম্পর্কে বেশি জানি না, তবে…", "I don’t know much about flowers, but I like having them at home."),
      phrase("They’re used for…", "এগুলো …-এর জন্য ব্যবহৃত হয়", "They’re used for weddings, mostly."),
      phrase("My favourite is…", "আমার প্রিয়…", "My favourite is the marigold — simple and bright."),
    ],
    questions: [
      q(
        "Do you like flowers?",
        "ফুল ভালো লাগে?",
        "A yes/no answer that must go beyond 'yes'. Call on the second-hand route if you have no strong interest.",
        ["Answer", "Favourite type or use", "Where you see them", "Personal memory"],
        ["Yes, I do — especially ___ , because ___ .", "Yes, I do — especially marigolds, because they remind me of winter weddings."],
        "Yes, I like flowers. My favourite is rose. We have some flowers in our balcony and my mother takes care of them.",
        "I do, though I’m no expert. I like marigolds mainly because of the association — they’re everywhere at weddings, and the smell takes me back to my cousin’s wedding. We also keep a couple of plants on our balcony, which my mother looks after.",
        [fix("I am having two flowers plant in balcony.", "We have a couple of flower plants on the balcony.", "Habitual possession uses 'have'; add 'the' before balcony.")],
        ["marigolds at weddings", "plants on the balcony", "simple and bright"],
        ["When do people give flowers in your country?"],
      ),
    ],
  }),
  topic({
    slug: "nature",
    title: "Nature",
    banglaTitle: "প্রকৃতি",
    summary: "Nature, greenery and cities — ideal for contrast, and easy to keep honest by talking about your own area.",
    tags: ["part 1", "environment", "core"],
    vocabulary: [
      vocab("greenery", "noun", "সবুজ", "There isn’t much greenery around my area."),
      vocab("scenery", "noun", "দৃশ্য", "The scenery in Sylhet is lovely."),
      vocab("fresh air", "noun", "নিরাপদ বাতাস", "I go to the park for some fresh air."),
      vocab("open space", "noun", "খোলা জায়গা", "Cities need more open space."),
      vocab("in the countryside", "phrase", "গ্রামে", "My uncle lives in the countryside."),
      vocab("peaceful", "adjective", "শান্ত", "It’s peaceful compared with the city."),
    ],
    phrases: [
      phrase("What I like about nature is…", "প্রকৃতিতে যা ভালো লাগে…", "What I like about nature is how quiet it gets."),
      phrase("It’s a break from the noise", "কোলাহল থেকে বিরতি", "It’s a break from the traffic noise."),
      phrase("We don’t get much of it in the city", "শহরে খুব বেশি পাওয়া যায় না", "We don’t get much greenery in the city."),
    ],
    questions: [
      q(
        "Do you like being close to nature?",
        "প্রকৃতির কাছে থাকতে ভালো লাগে?",
        "Preference + comparison + a specific place.",
        ["Answer", "Where you go", "Why", "City vs countryside"],
        ["Yes, I do — I ___ whenever ___ , because ___ .", "Yes, I do — I go to the botanical garden whenever I need to think, because it’s quiet."],
        "Yes, I like nature. When I have free time, I go to a park near my house. It is very peaceful and I can relax there.",
        "I do, and I notice it more now than I used to. Whenever things get stressful, I walk around the park near my area — it’s nothing special, but the trees and the quiet make a difference. What I miss about the countryside is the pace: everything slows down.",
        [fix("I like to go in nature.", "I like being in nature. / I like spending time in nature.", "'in nature' needs 'being' or 'spending time'.")],
        ["spend time in nature", "a nearby park", "slower pace of life"],
        ["Is there enough nature in your city?"],
      ),
    ],
  }),
  topic({
    slug: "music",
    title: "Music",
    banglaTitle: "সংগীত",
    summary: "Genre, mood and effect. Learn to say what music does for you rather than only naming artists.",
    tags: ["part 1", "leisure", "core"],
    vocabulary: [
      vocab("genre", "noun", "ধরন", "I listen to a mix of genres, mostly soft rock."),
      vocab("relaxing", "adjective", "মন শান্ত করা", "Instrumental music is relaxing for me."),
      vocab("lyrics", "noun", "গানের কথা", "I usually pay attention to the lyrics."),
      vocab("background music", "noun", "নেপথ্য সংগীত", "I put on background music while studying."),
      vocab("live concert", "noun", "সরাসরি কনসার্ট", "I’ve never been to a live concert."),
      vocab("cheer up", "phrasal verb", "মন ভালো করা", "Upbeat music cheers me up."),
    ],
    phrases: [
      phrase("I’m quite into…", "আমি … পছন্দ করি", "I’m quite into soft rock and a bit of classical."),
      phrase("It depends on my mood", "মুড অনুযায়ী বদলায়", "It depends on my mood — calm music while studying, upbeat when I’m tired."),
      phrase("It helps me concentrate", "মনোযোগ বাড়াতে সাহায্য করে", "Instrumental music helps me concentrate."),
    ],
    questions: [
      q(
        "What kind of music do you like?",
        "কী ধরনের সংগীত পছন্দ?",
        "Genre + reason + when you listen.",
        ["Genre(s)", "Why", "When/where you listen", "One artist or song"],
        ["I’m into ___ , mainly because ___ . I usually listen while ___ .", "I’m into soft rock, mainly because it’s calming. I usually listen while studying."],
        "I like soft music and also folk songs. I listen to music in the evening when I am free. My favourite singer is Arijit Singh.",
        "Mostly soft rock and some classical, though my taste shifts depending on my mood. I usually have something playing quietly while I study — instrumentals, not songs with lyrics, otherwise I end up singing instead of working. Arijit Singh is probably my most-played artist.",
        [fix("I am listening music in free time.", "I listen to music in my free time.", "Listen needs 'to'; habits use present simple.")],
        ["soft rock", "instrumental while studying", "depends on my mood"],
        ["Has your taste in music changed over time?"],
      ),
    ],
  }),
  topic({
    slug: "movies",
    title: "Movies",
    banglaTitle: "সিনেমা",
    summary: "Films, cinemas and streaming — genre, story and a recommendation make a complete answer.",
    tags: ["part 1", "entertainment", "core"],
    vocabulary: [
      vocab("plot", "noun", "কাহিনি", "The plot was quite predictable."),
      vocab("subtitle", "noun", "সাবটাইটেল", "I watch English films with subtitles."),
      vocab("gripping", "adjective", "মোহিত করা", "The first half was really gripping."),
      vocab("streaming", "noun", "স্ট্রিমিং", "I mostly watch films on streaming platforms."),
      vocab("go to the cinema", "phrase", "সিনেমা হলে যাওয়া", "We go to the cinema maybe once every two months."),
      vocab("recommend", "verb", "সুপারিশ করা", "I’d recommend it if you like slow stories."),
    ],
    phrases: [
      phrase("My favourite is…", "আমার প্রিয়…", "My favourite is a Bengali film called…"),
      phrase("It’s about…", "এটি … নিয়ে", "It’s about a family that moves to the city."),
      phrase("I’d recommend it because…", "সুপারিশ করব কারণ…", "I’d recommend it because the acting feels real."),
    ],
    questions: [
      q(
        "Do you prefer watching films at home or at the cinema?",
        "ঘরে দেখতে পছন্দ না হলে গিয়ে?",
        "A preference question: choose, justify, and allow the other side.",
        ["Preference", "Reason", "How often", "One film example"],
        ["I prefer ___ , mainly because ___ , although ___ .", "I prefer watching at home, mainly because it’s cheaper, although the big screen is better for action films."],
        "I prefer watching at home. It is comfortable and I can pause the film. But sometimes going to the cinema is nice because the screen is very big.",
        "At home, mostly — it’s cheaper and I can pause whenever I want, which matters if I’m tired. That said, there’s something about the cinema for a big action film; the sound alone makes it worth the ticket once in a while.",
        [fix("I am preferring cinema than home.", "I prefer the cinema to watching at home.", "'prefer A to B', not 'than'; no continuous form.")],
        ["watch at home", "the big screen", "pause anytime"],
        ["What kind of films do you enjoy?"],
      ),
    ],
  }),
];
