import type { Part2Category } from "../schema";
import { cat, fix, vocab } from "../content-builders";

const v = vocab;

/** Part 2 cue-card categories. Each category carries an idea lens, story
 *  advice, vocabulary, sentence structures, full cue cards at two levels and
 *  the mistakes that appear most often in that category. */
export const part2Categories: Part2Category[] = [
  cat({
    slug: "people",
    title: "People",
    banglaTitle: "মানুষ",
    shape: "person",
    summary: "The largest cue-card family: family members, friends, teachers, famous people, someone you admire.",
    ideaLens: {
      label: "Who?",
      prompts: [
        "Who are they, and how do you know them?",
        "What do they look like, or how do they come across?",
        "What is their personality — with one example of that personality",
        "What do you do together, or what did they do for you?",
        "Why do they matter to you, and what is one moment you remember?",
      ],
    },
    storyAdvice: [
      "Pick someone you have actually spent time with — a teacher, a cousin, a colleague. Real details are easier to produce and sound genuine.",
      "Anchor the personality in one incident: 'She’s patient — she once explained the same maths problem four times without sighing.'",
      "Save one sentence for why they matter to you. That answers the final bullet and closes the story.",
    ],
    vocabulary: [
      v("supportive", "adjective", "সহযোগী", "He’s been really supportive since I started university."),
      v("down to earth", "phrase", "সহজ ও বিনয়ী", "Despite his success, he’s very down to earth."),
      v("get on well with", "phrase", "ভালো সম্পর্ক থাকা", "I get on well with her because we think alike."),
      v("look up to", "phrasal verb", "শ্রদ্ধা করা", "I look up to my uncle for how he handles pressure."),
      v("sense of humour", "noun", "রসবোধ", "He has a dry sense of humour that I enjoy."),
    ],
    structures: [
      { template: "The person I’d like to talk about is ___, who ___ .", example: "The person I’d like to talk about is my cousin, who lives about ten minutes away.", note: "Relative clause in the first sentence buys time and adds detail." },
      { template: "What I admire most about ___ is ___ , because ___ .", example: "What I admire most about her is how calm she stays, because I’m the opposite." },
      { template: "I remember one time when ___ , and that’s when I realised ___ .", example: "I remember one time when I panicked before an exam, and that’s when I realised how much she helped me." },
    ],
    cueCards: [
      {
        prompt: "Describe a person you admire.",
        bullets: ["who this person is", "how you know them", "what they are like", "and explain why you admire them"],
        prepNotes: ["cousin", "same area", "calm, patient", "helps everyone", "exam panic story", "never complains", "want to be like her"],
        band6: "I would like to talk about my cousin. She is about five years older than me. She is very calm and patient. She always helps me with my studies when I have problems. I admire her because she never gets angry.",
        band65: "I’d like to talk about my cousin, who lives about ten minutes from my house. She’s five years older, and we’ve grown up together. The thing I admire most is how calm she stays under pressure — she finished her master’s while working, and I never once heard her complain. There was a time before my exams when I completely panicked, and she just sat with me and worked through my notes, question by question. That’s the kind of person I’d like to become.",
        whyItWorks: [
          "Opens with a relative clause, then a location detail (easy, natural)",
          "Names the quality (calm under pressure) and immediately proves it with evidence",
          "Includes a specific remembered incident — the detail that makes it sound real",
          "Closes with a reflection that answers 'why you admire them'",
        ],
      },
    ],
    corrections: [
      fix("“He is a person who he always helps others.”", "“He’s someone who always helps others.”", "Do not repeat the subject pronoun after 'who'."),
      fix("“She is very much kind and honest lady.”", "“She’s a very kind and honest person.”", "Use 'person' rather than 'lady'; drop 'very much'."),
      fix("“I am admiring him from my childhood.”", "“I’ve admired him since I was a child.”", "'admire' is a state verb; use present perfect for something continuing."),
    ],
    practiceCards: [
      "Describe a family member you spend a lot of time with.",
      "Describe a teacher who influenced you.",
      "Describe a friend who is very different from you.",
      "Describe someone who has helped you recently.",
    ],
  }),
  cat({
    slug: "places",
    title: "Places",
    banglaTitle: "স্থান",
    shape: "place",
    summary: "Cafés, parks, markets, cities, your own home — atmosphere and personal meaning matter more than description.",
    ideaLens: {
      label: "Where?",
      prompts: [
        "Where is it, and how often do you go?",
        "What does it look like, to someone arriving for the first time?",
        "What is the atmosphere like, and what do people do there?",
        "When did you first go, and who with?",
        "Why is it memorable to you specifically?",
      ],
    },
    storyAdvice: [
      "Move quickly past 'it is beautiful'. Give one sensory detail instead: the noise, the smell, the light.",
      "Describe people in the place doing something — a place only exists in the story through the people in it.",
      "Explain the personal meaning at the end; that is where the second minute lives.",
    ],
    vocabulary: [
      v("lively", "adjective", "প্রাণবন্ত", "The market is really lively in the mornings."),
      v("peaceful", "adjective", "শান্ত", "It’s peaceful compared with the main road."),
      v("get crowded", "phrase", "ভিড় হয়ে যাওয়া", "It gets crowded after five o’clock."),
      v("within walking distance", "phrase", "হাঁটার দূরত্বে", "It’s within walking distance of my college."),
      v("a change of scene", "phrase", "পরিবেশ পরিবর্তন", "I go there for a change of scene."),
    ],
    structures: [
      { template: "The place I’d like to talk about is ___ , which is ___ .", example: "The place I’d like to talk about is a café near my college, which is fairly new." },
      { template: "What makes it special is ___ , especially when ___ .", example: "What makes it special is the quiet, especially in the mornings when there’s nobody there." },
      { template: "I first went there ___ , and I’ve been going ___ ever since.", example: "I first went there during my exams, and I’ve been going every week ever since." },
    ],
    cueCards: [
      {
        prompt: "Describe a place you like to visit in your free time.",
        bullets: ["where it is", "how often you go there", "what you do there", "and explain why you like it"],
        prepNotes: ["café near college", "twice a month", "study + chai", "old friend works there", "quiet afternoons", "cheap", "feels calm"],
        band6: "I would like to talk about a café near my college. It is about ten minutes from my house. I go there two times a month with my friends. We drink tea and talk about our studies. I like it because it is quiet and the price is low.",
        band65: "I’d like to talk about a small café near my college — it’s about a ten-minute walk, and I go there roughly twice a month. I usually take my books and sit at the back; a friend of mine works there, so we end up chatting more than studying. The main reason I like it is that it’s genuinely quiet in the afternoons — there’s none of the traffic noise you get elsewhere — so I can actually think for an hour.",
        whyItWorks: [
          "Location and frequency in the first sentence — the bullets are answered without listing",
          "One specific person (a friend who works there) makes the place real",
          "Reasons are concrete: quiet, no traffic noise, can think",
          "Ends on how the place affects the speaker rather than a general statement",
        ],
      },
    ],
    corrections: [
      fix("“It is a very much beautiful place.”", "“It’s a really beautiful place.”", "'Very much' does not modify adjectives; use 'really' or 'particularly'."),
      fix("“I am going there since two years.”", "“I’ve been going there for two years.”", "Continuing action → present perfect continuous, and 'for' + duration."),
      fix("“The place is full with people.”", "“The place is full of people.”", "'Full of', not 'full with'."),
    ],
    practiceCards: [
      "Describe a quiet place you like to go to.",
      "Describe a market or shopping area you visit.",
      "Describe a place you would like to live in the future.",
      "Describe a place you visited that surprised you.",
    ],
  }),
  cat({
    slug: "objects",
    title: "Objects and possessions",
    banglaTitle: "বস্তু ও সম্পদ",
    shape: "object",
    summary: "Phones, bicycles, gifts, gadgets — the trick is telling the story of the object rather than describing it.",
    ideaLens: {
      label: "What?",
      prompts: [
        "What is it, and how would you describe it?",
        "How did you get it — bought, gifted, inherited?",
        "How often do you use it, and for what?",
        "Why is it important to you?",
        "What memory do you associate with it?",
      ],
    },
    storyAdvice: [
      "Avoid the phone and the laptop if you can — everyone picks them. Choose something with a story: a bicycle, a watch, a book.",
      "Use the 'how you got it' bullet to introduce people; every object arrives through somebody.",
      "End with a memory, not a summary. 'I still remember the shop' beats 'so it is very important to me'.",
    ],
    vocabulary: [
      v("second-hand", "adjective", "পুরোনো/ব্যবহৃত", "I bought it second-hand from a friend."),
      v("sentimental value", "noun", "আবেগের মূল্য", "It doesn’t cost much, but it has sentimental value."),
      v("wear out", "phrasal verb", "ক্ষয়ে যাওয়া", "It’s worn out but still works."),
      v("come in handy", "phrase", "কাজে আসা", "It comes in handy when I travel."),
      v("keep it in good condition", "phrase", "ভালো অবস্থায় রাখা", "I try to keep it in good condition."),
    ],
    structures: [
      { template: "The object I’d like to talk about is ___ , which ___ .", example: "The object I’d like to talk about is my bicycle, which I’ve had for three years." },
      { template: "I got it from ___ , and at first ___ .", example: "I got it from my uncle, and at first I thought it was too old." },
      { template: "What makes it valuable to me is ___ , not ___ .", example: "What makes it valuable to me is the daily use, not the price." },
    ],
    cueCards: [
      {
        prompt: "Describe something you own that is important to you.",
        bullets: ["what it is", "how you got it", "how often you use it", "and explain why it is important to you"],
        prepNotes: ["bicycle", "uncle’s, 2022", "college commute", "saves fare", "keeps me fit", "chain broke once", "use it daily"],
        band6: "I would like to talk about my bicycle. It is not new. My uncle gave it to me two years ago. I use it every day to go to college because it saves money. It is important for me because I don’t need to wait for the bus.",
        band65: "The thing I’d like to talk about is my bicycle, which my uncle gave me about two years ago — he was upgrading, so it’s second-hand but in decent condition. I use it almost every day for college; it saves the fare and it means I don’t have to wait around for buses. It’s genuinely important to me for that reason — but also because it’s the only thing that gets me any exercise at all.",
        whyItWorks: [
          "Story of acquisition with a reason (uncle was upgrading) — small detail, big authenticity",
          "Practical benefit (saves fare, avoids waiting) plus a personal benefit (exercise)",
          "Uses present simple accurately for repeated actions",
          "Ends with a personal reflection rather than a generic summary",
        ],
      },
    ],
    corrections: [
      fix("“I am using it from two years.”", "“I’ve been using it for two years.”", "Present perfect continuous with 'for' + duration."),
      fix("“It is made of plastics.”", "“It’s made of plastic.”", "Materials are uncountable in this pattern."),
      fix("“It has much sentimental value for me.”", "“It has a lot of sentimental value for me.”", "'Much' is used mostly in negatives and questions."),
    ],
    practiceCards: [
      "Describe an object you use every day.",
      "Describe a gift you received that you still use.",
      "Describe something you bought that you regret buying.",
      "Describe a piece of technology you find useful.",
    ],
  }),
  cat({
    slug: "experiences",
    title: "Experiences",
    banglaTitle: "অভিজ্ঞতা",
    shape: "experience",
    summary: "Times you were late, surprised, proud or worried — every experience card follows problem → feeling → result.",
    ideaLens: {
      label: "When?",
      prompts: [
        "When and where did it happen?",
        "Who was involved?",
        "What exactly happened, in order?",
        "What went wrong, or what changed?",
        "How did you feel, and what was the result?",
      ],
    },
    storyAdvice: [
      "Keep one main event. Two events halve the detail you can give to each.",
      "Use past continuous for background and past simple for the main actions — it sounds natural immediately.",
      "The result sentence is your ending: what changed because of it.",
    ],
    vocabulary: [
      v("unexpected", "adjective", "অপ্রত্যাশিত", "It was completely unexpected."),
      v("embarrassing", "adjective", "লজ্জাজনক", "It was embarrassing at the time."),
      v("in the end", "phrase", "শেষ পর্যন্ত", "In the end, everything worked out."),
      v("look back on", "phrasal verb", "ফিরে দেখা", "I look back on it quite fondly now."),
      v("learn a lesson", "phrase", "শিক্ষা নেওয়া", "I definitely learned a lesson that day."),
    ],
    structures: [
      { template: "This happened about ___ ago, when I was ___ .", example: "This happened about two years ago, when I was in my first year at university." },
      { template: "At first I thought ___ , but then ___ .", example: "At first I thought it would be fine, but then I realised I’d missed the bus." },
      { template: "In the end ___ , which taught me ___ .", example: "In the end everything worked out, which taught me to double-check my alarms." },
    ],
    cueCards: [
      {
        prompt: "Describe a time when you were late for something important.",
        bullets: ["what the occasion was", "why you were late", "what happened", "and explain how you felt about it"],
        prepNotes: ["university exam", "alarm failed", "missed bus", "ran 20 min", "arrived late", "felt awful", "told the invigilator", "set two alarms"],
        band6: "I want to talk about a time I was late for my university exam. My alarm did not work, so I woke up late. I missed the bus and I had to run. When I arrived, the exam had already started. I felt very bad.",
        band65: "I’d like to talk about a morning last year when I was late for a university exam. My alarm simply didn’t go off — I still don’t know why — so I woke up forty minutes late and missed the bus I always take. I ended up running most of the way, which is not something I recommend in Dhaka humidity. By the time I got there the exam had started, and I had to explain everything to the invigilator, who was far more understanding than I expected. I felt awful for the first twenty minutes, but it taught me to set two alarms on exam days.",
        whyItWorks: [
          "Clear time setting, then a sequence of causes and events",
          "Background detail (past continuous) mixed with main actions (past simple)",
          "Feeling plus a small human detail (the invigilator)",
          "Ends with the lesson — a natural way to answer 'how you felt'",
        ],
      },
    ],
    corrections: [
      fix("“When I reached, the exam already start.”", "“When I arrived, the exam had already started.”", "Past perfect for the earlier event; 'arrive' not 'reach' here."),
      fix("“I was feeling very much tension.”", "“I was really nervous.”", "Use 'nervous'/'stressed'; 'tension' is a noun and 'very much' does not fit."),
      fix("“I didn’t knew the way.”", "“I didn’t know the way.”", "After 'didn't', use the base verb."),
    ],
    practiceCards: [
      "Describe a time you helped someone.",
      "Describe a time you were surprised.",
      "Describe a difficult decision you had to make.",
      "Describe a time you got lost.",
    ],
  }),
  cat({
    slug: "events",
    title: "Events",
    banglaTitle: "অনুষ্ঠান ও ঘটনা",
    shape: "event",
    summary: "Weddings, festivals, sports events, ceremonies — the story arc is naturally chronological, which makes them easy.",
    ideaLens: {
      label: "When?",
      prompts: [
        "What was the event, and when did it happen?",
        "Where was it, and who was there?",
        "What happened first, and then what?",
        "What was the most memorable moment?",
        "How did you feel, and what did you take from it?",
      ],
    },
    storyAdvice: [
      "Follow the chronology rather than describing the venue — events are stories by nature.",
      "Include one small human detail: who cried, who arrived late, what the food was like.",
      "Do not try to describe everything. Two or three specific moments make a stronger answer than a full itinerary.",
    ],
    vocabulary: [
      v("get together", "phrasal verb", "একত্র হওয়া", "The whole family got together for it."),
      v("atmosphere", "noun", "পরিবেশ", "The atmosphere was relaxed."),
      v("memorable", "adjective", "স্মরণীয়", "It was a memorable evening."),
      v("take part in", "phrase", "অংশ নেওয়া", "I took part in the ceremony."),
      v("it went on until", "phrase", "… পর্যন্ত চলেছিল", "It went on until midnight."),
    ],
    structures: [
      { template: "It took place ___ , and I was there with ___ .", example: "It took place last December, and I was there with my cousins." },
      { template: "What I remember most clearly is ___ .", example: "What I remember most clearly is how loud the music was." },
      { template: "By the end of it, ___ .", example: "By the end of it, nobody wanted to go home." },
    ],
    cueCards: [
      {
        prompt: "Describe an important event you attended.",
        bullets: ["what the event was", "where and when it happened", "who you went with", "and explain why it was important to you"],
        prepNotes: ["cousin’s wedding", "December, village", "with family", "three days", "lots of food", "mehndi night", "all cousins together", "rare occasion"],
        band6: "I would like to talk about my cousin’s wedding. It was in December, in our village. I went with my parents and my brother. The wedding continued for three days. I enjoyed it because I met all my cousins there.",
        band65: "I’d like to talk about my cousin’s wedding last December, which took place in our village over three days. I went with my parents and my brother, and honestly the whole extended family was there — some of them I hadn’t seen in years. The mehndi night stands out: all of us cousins sat on the floor in one room, and it went on until two in the morning. It mattered to me because that kind of gathering barely happens now, with everyone scattered across different cities.",
        whyItWorks: [
          "Event, time, place and company all answered in the first two sentences",
          "One specific occasion (mehndi night) instead of describing all three days",
          "A reason that reflects a real social change — this reads as thought, not memorisation",
          "Vocabulary is ordinary but precise: extended family, scattered across",
        ],
      },
    ],
    corrections: [
      fix("“The marriage was happened in our village.”", "“The wedding took place in our village.”", "A wedding 'takes place'; 'happened' cannot take 'was'."),
      fix("“Many many relatives was present.”", "“There were a lot of relatives there.”", "Use 'there were'; do not repeat 'many'."),
      fix("“We enjoyed a lot in that day.”", "“We really enjoyed that day.”", "'Enjoy' takes an object; avoid 'enjoyed a lot'."),
    ],
    practiceCards: [
      "Describe a wedding you attended.",
      "Describe a festival you celebrated with your family.",
      "Describe a sports event you watched or played in.",
      "Describe a ceremony that was important in your community.",
    ],
  }),
  cat({
    slug: "activities",
    title: "Activities and hobbies",
    banglaTitle: "কার্যক্রম ও শখ",
    shape: "activity",
    summary: "Sports, cooking, cycling, gaming — talk about how you started, why you continue and what it gives you.",
    ideaLens: {
      label: "What?",
      prompts: [
        "What is the activity, and how did you start?",
        "How often do you do it, and where?",
        "Do you do it alone or with others?",
        "Why do you keep doing it?",
        "What has it given you beyond enjoyment?",
      ],
    },
    storyAdvice: [
      "Say who introduced you to it. Every activity has an entry point, and it gives you a person to mention.",
      "Describe what it feels like while you are doing it — this is the detail most learners skip.",
      "Finish with what it gives you: relaxation, fitness, a group of friends, perspective.",
    ],
    vocabulary: [
      v("take up", "phrasal verb", "শুরু করা (শখ)", "I took it up during the holidays."),
      v("keep me occupied", "phrase", "সময় কাটানো", "It keeps me occupied when I’m bored."),
      v("a bit of exercise", "phrase", "একটু ব্যায়াম", "It gives me a bit of exercise at least."),
      v("switch off", "phrasal verb", "মন হালকা করা", "It helps me switch off from studies."),
      v("get better at", "phrase", "উন্নতি করা", "I’m slowly getting better at it."),
    ],
    structures: [
      { template: "The activity I’d like to talk about is ___ , which I took up ___ .", example: "The activity I’d like to talk about is cycling, which I took up two years ago." },
      { template: "I usually ___ , and I find it ___ .", example: "I usually go in the evenings, and I find it almost meditative." },
      { template: "It’s given me ___ as well as ___ .", example: "It’s given me a group of friends as well as better fitness." },
    ],
    cueCards: [
      {
        prompt: "Describe an activity you enjoy doing in your free time.",
        bullets: ["what the activity is", "how often you do it", "who you do it with", "and explain why you enjoy it"],
        prepNotes: ["cycling", "evenings", "alone or with cousin", "around the area", "fresh air", "switch off", "getting fitter", "started 2023"],
        band6: "I want to talk about cycling. I usually cycle in the evening for about thirty minutes. Sometimes my cousin comes with me. I enjoy it because it is relaxing and I can see my area and also it is good for health.",
        band65: "The activity I enjoy most is cycling — I usually go in the evenings, for half an hour or so around my area. Sometimes my cousin joins me, though I’m happy either way. What I like is that it’s the only part of my day where I’m not looking at a screen; I notice things — a new shop, a game of cricket, the smell of someone’s kitchen. It’s relaxing and it keeps me reasonably fit, which I appreciate more every year.",
        whyItWorks: [
          "Duration, frequency and companion answered without listing",
          "Specific sensory details (a game of cricket, the smell of a kitchen) — the detail step of the story engine",
          "Two benefits: mental and physical",
          "Natural hedged phrase 'though I’m happy either way' adds flexibility",
        ],
      },
    ],
    corrections: [
      fix("“I am doing cycling daily.”", "“I cycle every day.”", "Use the verb 'cycle'; habits take present simple."),
      fix("“It is good for my health also it is relaxing.”", "“It’s good for my health, and it’s relaxing too.”", "Two independent clauses need a conjunction and a comma."),
      fix("“I have interest on music.”", "“I’m interested in music.”", "'Interested in' is the fixed collocation."),
    ],
    practiceCards: [
      "Describe a hobby you have had for a long time.",
      "Describe a physical activity you do regularly.",
      "Describe something you do to relax.",
      "Describe an activity you would like to try for the first time.",
    ],
  }),
  cat({
    slug: "skills",
    title: "Skills",
    banglaTitle: "দক্ষতা",
    shape: "skill",
    summary: "Driving, cooking, swimming, coding — the structure is: why you learned it, how, what was hard, how you use it.",
    ideaLens: {
      label: "What?",
      prompts: [
        "What is the skill and why did you want to learn it?",
        "How did you learn — alone, teacher, practice?",
        "What was the hardest part?",
        "How well can you do it now?",
        "How does it help you in daily life?",
      ],
    },
    storyAdvice: [
      "The hardest part is the most interesting sentence in this cue card. Be honest about it.",
      "Describe a specific moment where the skill clicked, or where it went wrong.",
      "End with how the skill is used now — future or present forms give you range.",
    ],
    vocabulary: [
      v("pick up", "phrasal verb", "শিখে ফেলা (সহজে)", "I picked it up quickly, actually."),
      v("trial and error", "phrase", "ভুল করে শেখা", "It was mostly trial and error."),
      v("master", "verb", "আয়ত্ত করা", "I still haven’t mastered it."),
      v("on my own", "phrase", "নিজে নিজে", "I learned it mostly on my own."),
      v("come in useful", "phrase", "কাজে আসা", "It comes in useful quite often."),
    ],
    structures: [
      { template: "The skill I’d like to talk about is ___ , which I learned ___ .", example: "The skill I’d like to talk about is driving, which I learned during my second year at university." },
      { template: "The difficult part was ___ , because ___ .", example: "The difficult part was the clutch, because I couldn’t feel when to change gear." },
      { template: "These days I ___ , and it ___ .", example: "These days I drive my father to work sometimes, and it saves him a lot of time." },
    ],
    cueCards: [
      {
        prompt: "Describe a skill you learned that was difficult at first.",
        bullets: ["what the skill was", "how you learned it", "why it was difficult", "and explain how it helps you now"],
        prepNotes: ["driving", "instructor 2023", "clutch hard", "stalled 6 times", "3 months", "nervous at first", "drive to market", "saves time"],
        band6: "I want to talk about driving. I learned it from an instructor in 2023. It was difficult for me because I could not control the clutch. I practiced for three months. Now I drive my father to the market sometimes and it saves time.",
        band65: "The skill I’d like to talk about is driving, which I learned with a professional instructor back in 2023. What made it hard was the clutch — I stalled the car six times on my first day, and honestly I nearly gave up. Three months of practice later it clicked, and now I drive my father to the market once a week, which saves him a lot of hassle. The interesting part is that the skill stopped being scary once I accepted that I’d make a few mistakes first.",
        whyItWorks: [
          "Concrete difficulty with a specific number (six stalls on day one)",
          "A small honest admission ('nearly gave up') — examiners hear authenticity",
          "Present-day application answers the final bullet naturally",
          "Closing reflection adds development without a memorised-sounding conclusion",
        ],
      },
    ],
    corrections: [
      fix("“I learned driving from my uncle.”", "“I learned to drive from my uncle.”", "Skills take 'learn to + verb'."),
      fix("“It was very difficult for to do.”", "“It was difficult for me to do.”", "Do not drop the object pronoun after 'for'."),
      fix("“Now I can able to drive.”", "“Now I’m able to drive.”", "Use either 'can' or 'be able to', never both."),
    ],
    practiceCards: [
      "Describe a practical skill you have.",
      "Describe something you would like to learn how to do.",
      "Describe a skill you learned from a family member.",
      "Describe something you found difficult at first but now enjoy.",
    ],
  }),
  cat({
    slug: "books-movies",
    title: "Books, films and media",
    banglaTitle: "বই, সিনেমা ও মিডিয়া",
    shape: "media",
    summary: "Books, films, TV programmes and songs — the trick is to describe one scene or one moment, not the whole plot.",
    ideaLens: {
      label: "What?",
      prompts: [
        "What is the book or film, and when did you encounter it?",
        "What is it about — in two sentences, not a summary",
        "Which moment, scene or chapter stands out?",
        "Why did it stay with you?",
        "Would you recommend it, and to whom?",
      ],
    },
    storyAdvice: [
      "Never attempt the full plot. Choose one scene and describe what happens to the people in it.",
      "Say who recommended it — this adds a person and a reason in one go.",
      "End with a recommendation and a caveat ('though not everyone would enjoy it').",
    ],
    vocabulary: [
      v("come across", "phrasal verb", "দেখতে পাওয়া/খুঁজে পাওয়া", "I came across it in a bookshop."),
      v("gripping", "adjective", "মোহিত করা", "The first half was really gripping."),
      v("relatable", "adjective", "সহজে সম্পর্ক করা যায়", "The characters felt relatable."),
      v("plot", "noun", "কাহিনির ধারা", "The plot was predictable but enjoyable."),
      v("recommend", "verb", "সুপারিশ করা", "I’d recommend it to anyone who…"),
    ],
    structures: [
      { template: "The book I’d like to talk about is ___ , which I ___ .", example: "The book I’d like to talk about is a Bengali novel called…, which my teacher recommended." },
      { template: "There’s one scene where ___ , and that’s the part I remember." , example: "There’s one scene where the family argues about money, and that’s the part I remember." },
      { template: "I’d recommend it to ___ , though ___ .", example: "I’d recommend it to anyone who enjoys slow stories, though it isn’t for everyone." },
    ],
    cueCards: [
      {
        prompt: "Describe a book you enjoyed reading.",
        bullets: ["what the book was", "how you found out about it", "what it was about", "and explain why you enjoyed it"],
        prepNotes: ["Bengali novel", "teacher recommended", "family moving to city", "one argument scene", "read in 3 weeks", "felt real", "want to reread"],
        band6: "I want to talk about a Bengali novel I read last year. My teacher told me about it. The story is about a family who move from a village to Dhaka. I liked it because the story was interesting and I could understand the characters.",
        band65: "I’d like to talk about a Bengali novel I read last year, which my literature teacher recommended — I probably wouldn’t have picked it up otherwise. It’s about a family that moves from a village to Dhaka, and the way each of them adjusts differently. There’s one scene where they argue about money after a wedding, and it felt uncomfortably familiar — I could hear my own relatives in the dialogue. That’s the main reason I enjoyed it: it wasn’t dramatic, it just felt true.",
        whyItWorks: [
          "How the speaker found the book is answered with a real reason",
          "One scene instead of a plot summary — far easier to deliver and more vivid",
          "A personal comparison ('I could hear my own relatives') shows flexibility",
          "Ends with a judgement ('it just felt true') rather than a generic conclusion",
        ],
      },
    ],
    corrections: [
      fix("“I am reading this book from last week.”", "“I’ve been reading this book since last week.”", "Use present perfect continuous with 'since' + point in time."),
      fix("“The book is about a story of a family.”", "“The book is about a family.”", "'About a story of' is redundant."),
      fix("“I suggest you to read it.”", "“I’d recommend reading it.”", "'Suggest' does not take 'you to'; use 'recommend' + -ing."),
    ],
    practiceCards: [
      "Describe a film that made you think.",
      "Describe a TV programme you watch regularly.",
      "Describe a song that means something to you.",
      "Describe a story you remember from childhood.",
    ],
  }),
  cat({
    slug: "travel-journeys",
    title: "Travel and journeys",
    banglaTitle: "ভ্রমণ ও যাত্রা",
    shape: "place",
    summary: "A trip, a journey, a holiday — the story arrives with its own structure: plan, journey, surprise, memory.",
    ideaLens: {
      label: "Where?",
      prompts: [
        "Where did you go, and who with?",
        "How did you travel there (this detail always adds value)?",
        "What did you do, and what surprised you?",
        "Was there a problem, or an unexpected moment?",
        "Why does it stay in your memory?",
      ],
    },
    storyAdvice: [
      "The journey itself is often more interesting than the destination — delays, conversations, food on the way.",
      "Include one problem. Trouble makes stories memorable and gives you contrast and past perfect practice.",
      "Finish with a person or a feeling, not a review of the place.",
    ],
    vocabulary: [
      v("set off", "phrasal verb", "রওনা হওয়া", "We set off at five in the morning."),
      v("worth the trip", "phrase", "যাওয়ার মতোই", "It was long, but worth the trip."),
      v("off the beaten track", "phrase", "কম পরিচিত জায়গা", "It’s a bit off the beaten track."),
      v("breathtaking", "adjective", "শ্বাসরুদ্ধকর", "The view from the hill was breathtaking."),
      v("get stuck", "phrasal verb", "আটকে যাওয়া", "We got stuck on the highway for two hours."),
    ],
    structures: [
      { template: "We set off from ___ and travelled to ___ .", example: "We set off from Dhaka at night and travelled to Cox’s Bazar." },
      { template: "What surprised me was ___ , because ___ .", example: "What surprised me was how quiet the beach was in the morning." },
      { template: "Even now, ___ reminds me of that trip.", example: "Even now, the smell of salt reminds me of that trip." },
    ],
    cueCards: [
      {
        prompt: "Describe a journey you remember well.",
        bullets: ["where you went", "who you went with", "what happened during the journey", "and explain why you remember it"],
        prepNotes: ["night bus, Dhaka to Cox’s Bazar", "with 3 friends", "bus broke down", "waited 2 hours", "arrived at sunrise", "worried", "laughed after", "memory of the sunrise"],
        band6: "I want to talk about a journey to Cox’s Bazar. I went with three friends by bus at night. Our bus broke down on the way and we waited for two hours. We arrived at sunrise. I remember it because it was a long journey and we were tired.",
        band65: "I’d like to talk about a bus journey to Cox’s Bazar that I took with three friends. We set off from Dhaka at night, which seemed like a good idea at the time — until the bus broke down somewhere past Chattogram and we sat by the roadside for two hours. We were exhausted and slightly worried, but it turned out fine, because we arrived exactly as the sun came up over the beach. Even now, that sunrise is the thing I remember most; the delay somehow made it better.",
        whyItWorks: [
          "Transport, time and company answered in the opening sentence",
          "A problem in the middle — the detail that makes the story memorable",
          "Uses past perfect naturally ('we had been waiting' variants, 'seemed like a good idea at the time')",
          "Ends with an image, not a summary — this is what the examiner hears as development",
        ],
      },
    ],
    corrections: [
      fix("“We reached to Cox’s Bazar in the morning.”", "“We reached Cox’s Bazar in the morning.”", "'Reach' takes no preposition."),
      fix("“We were very much tired.”", "“We were exhausted / really tired.”", "Avoid 'very much' before adjectives."),
      fix("“It was a nice journey, I enjoyed a lot.”", "“It was a great journey, and I enjoyed it a lot.”", "Add the object 'it', and use 'a lot' at the end."),
    ],
    practiceCards: [
      "Describe a long journey you took.",
      "Describe a holiday you remember well.",
      "Describe a place you visited that was different from your expectations.",
      "Describe a trip that did not go as planned.",
    ],
  }),
  cat({
    slug: "decisions-problems",
    title: "Decisions and problems",
    banglaTitle: "সিদ্ধান্ত ও সমস্যা",
    shape: "decision",
    summary: "Difficult decisions, regrets, problems solved — the structure is choice → pressure → outcome → lesson.",
    ideaLens: {
      label: "What?",
      prompts: [
        "What was the decision or problem?",
        "Why did it matter at the time?",
        "What pressure or difficulty was involved?",
        "What did you decide or do?",
        "How did it turn out, and what did you learn?",
      ],
    },
    storyAdvice: [
      "Choose something ordinary — choosing a subject, moving city, lending money, missing an exam. Everyday problems are easier to explain honestly.",
      "Show the pressure: time, money, family expectations, or a deadline.",
      "Say what you learned. The lesson sentence is your 'why it matters' answer.",
    ],
    vocabulary: [
      v("come to a decision", "phrase", "সিদ্ধান্তে পৌঁছানো", "It took a week to come to a decision."),
      v("under pressure", "phrase", "চাপের মধ্যে", "I was under pressure from the deadline."),
      v("weigh up the options", "phrase", "বিকল্পগুলো ভাবা", "I weighed up the options for days."),
      v("in hindsight", "phrase", "পিছনে তাকালে বুঝি", "In hindsight, it was the right choice."),
      v("regret", "verb", "অনুশোচনা", "It’s the one thing I genuinely regret."),
    ],
    structures: [
      { template: "The problem was that ___ , and I had to ___ .", example: "The problem was that my results came out on the same day as the deadline, and I had to choose." },
      { template: "It was difficult because ___ , not because ___ .", example: "It was difficult because of the timing, not because of the decision itself." },
      { template: "Looking back, ___ — and now I ___ .", example: "Looking back, talking to my father first was the right move — and now I do that before anything big." },
    ],
    cueCards: [
      {
        prompt: "Describe a difficult decision you had to make.",
        bullets: ["what the decision was", "why it was difficult", "what you decided", "and explain how you feel about it now"],
        prepNotes: ["choose degree subject", "family wanted engineering", "I wanted business", "talked for days", "father’s advice", "chose business", "happy now", "learned to speak up"],
        band6: "I want to talk about choosing my subject at university. My family wanted me to study engineering but I wanted business. It was difficult because I didn’t want to disappoint them. In the end I chose business. Now I am happy with my decision.",
        band65: "One decision that was genuinely difficult was choosing my subject at university. My parents wanted engineering — not because they’d insisted, but because they thought it would be more secure — while I wanted business. I spent about two weeks weighing up the options, mostly because I didn’t want to disappoint them. What helped was talking to my father properly instead of arguing: he said the decision had to be mine, which removed most of the pressure. In hindsight, it was the right call — I actually enjoy what I study, and I’ve learned to say what I want before it becomes an argument.",
        whyItWorks: [
          "Shows the pressure (family expectations) rather than only the outcome",
          "Includes a turning point with a person — the detail that makes it a story",
          "Uses 'in hindsight' and present perfect naturally",
          "Ends with a lesson, which answers the 'how you feel now' bullet",
        ],
      },
    ],
    corrections: [
      fix("“I was confused what to do.”", "“I wasn’t sure what to do.”", "'Confused' needs 'about'; 'wasn’t sure what to do' is natural."),
      fix("“Finally I taken the decision.”", "“In the end, I made the decision.”", "'Take a decision' → 'make a decision'; use past simple."),
      fix("“I am regretting it now.”", "“I regret it now.”", "'Regret' is a state verb, not used in continuous form."),
    ],
    practiceCards: [
      "Describe a decision you made quickly.",
      "Describe a problem you solved.",
      "Describe something you regret doing.",
      "Describe a time you had to choose between two good options.",
    ],
  }),
  cat({
    slug: "achievements",
    title: "Achievements and proud moments",
    banglaTitle: "অর্জন ও গর্বের মুহূর্ত",
    shape: "achievement",
    summary: "Prizes, exams, competitions, personal goals — the structure is goal → effort → moment → meaning.",
    ideaLens: {
      label: "What?",
      prompts: [
        "What was the achievement, and when?",
        "What did you have to do to get there?",
        "Who helped or supported you?",
        "What was the moment you realised you’d done it?",
        "Why did it matter to you?",
      ],
    },
    storyAdvice: [
      "Choose something modest and real — passing a hard subject, running 5 km, finishing a project. Grand achievements are harder to describe convincingly.",
      "Spend at least half the answer on the effort, not the result. Effort is where the language lives.",
      "Describe the moment itself with a physical detail (who you called first, what you did).",
    ],
    vocabulary: [
      v("work towards", "phrasal verb", "লক্ষ্যের দিকে কাজ করা", "I worked towards it for six months."),
      v("proud of", "phrase", "গর্বিত", "I’m genuinely proud of that."),
      v("pay off", "phrasal verb", "ফল দেয়া", "All that effort paid off."),
      v("milestone", "noun", "মাইলফলক", "It felt like a milestone."),
      v("come a long way", "phrase", "অনেক এগিয়ে যাওয়া", "I’ve come a long way since then."),
    ],
    structures: [
      { template: "The achievement I’m most proud of is ___ , which happened ___ .", example: "The achievement I’m most proud of is passing my statistics exam, which happened last year." },
      { template: "It took ___ , and I had to ___ .", example: "It took six months, and I had to study an hour every morning before class." },
      { template: "When I saw ___ , I felt ___ .", example: "When I saw my result, I felt relieved more than anything." },
    ],
    cueCards: [
      {
        prompt: "Describe something you are proud of achieving.",
        bullets: ["what you achieved", "how long it took", "who helped you", "and explain why you are proud of it"],
        prepNotes: ["passed statistics", "hardest subject", "6 months", "friend tutored me", "failed first test", "studied mornings", "relieved", "proved I can"],
        band6: "I want to talk about passing my statistics exam. I failed the first test, so I studied hard for six months. My friend helped me with the difficult parts. I am proud because it was very difficult and I did not give up.",
        band65: "The achievement I’m most proud of is passing my statistics exam last year — which sounds minor, but it was the subject I genuinely thought I couldn’t do. I failed the first test badly, and after that I studied for about an hour every morning before class, for six months. A friend of mine, who’s much better at maths, sat with me every weekend and refused to just give me answers. When the result came out I felt relieved more than happy, honestly — and that’s why it matters: it proved to me that being bad at something isn’t permanent.",
        whyItWorks: [
          "Modest achievement, described with real effort — more convincing than a trophy",
          "Specific numbers: failed first test, an hour every morning, six months",
          "Including a helper adds a person and a small detail",
          "The final sentence explains the personal meaning — the 'why it matters' step",
        ],
      },
    ],
    corrections: [
      fix("“I am proud for my achievement.”", "“I’m proud of my achievement.”", "'Proud of', not 'proud for'."),
      fix("“It was very much difficult for achieve.”", "“It was really difficult to achieve.”", "'difficult to + verb'; avoid 'very much' with adjectives."),
      fix("“I successed in the exam.”", "“I succeeded in the exam.”", "'Success' is a noun; the verb is 'succeed'."),
    ],
    practiceCards: [
      "Describe a goal you achieved.",
      "Describe something you did that was difficult.",
      "Describe a time you surprised yourself.",
      "Describe something you worked hard for.",
    ],
  }),
  cat({
    slug: "education-work",
    title: "Education and work",
    banglaTitle: "শিক্ষা ও কাজ",
    shape: "experience",
    summary: "A subject you enjoyed, a school, a job, a colleague — the most predictable Part 2 family, and the easiest to prepare.",
    ideaLens: {
      label: "What?",
      prompts: [
        "What is it — subject, school, job or colleague?",
        "When and where did it happen?",
        "What did you actually do there?",
        "What did you learn from it?",
        "Why does it matter to you now?",
      ],
    },
    storyAdvice: [
      "Choose real detail over impressive titles: a specific class, a specific task, a specific colleague.",
      "Education cards benefit from one example of a lesson or a project you remember.",
      "End with how it shaped your plans — this lets you use future forms naturally.",
    ],
    vocabulary: [
      v("hands-on", "adjective", "হাতে-কলমে", "The practical classes were very hands-on."),
      v("deadline", "noun", "সময়সীমা", "We were working to a tight deadline."),
      v("colleague", "noun", "সহকর্মী", "A colleague showed me how to do it."),
      v("gain experience", "phrase", "অভিজ্ঞতা অর্জন", "I gained a lot of experience there."),
      v("career path", "noun", "কর্মজীবনের পথ", "It made me think about my career path."),
    ],
    structures: [
      { template: "___ was the subject/job I’d like to talk about, which I ___ .", example: "Accounting was the subject I’d like to talk about, which I started in 2022." },
      { template: "What made it interesting was ___ , for example ___ .", example: "What made it interesting was the practical side, for example preparing a real balance sheet." },
      { template: "It’s had an influence on me because now I ___ .", example: "It’s had an influence on me because now I actually enjoy numbers, which surprised everyone." },
    ],
    cueCards: [
      {
        prompt: "Describe a subject you enjoyed studying at school or university.",
        bullets: ["what the subject was", "when you studied it", "what you learned", "and explain why you enjoyed it"],
        prepNotes: ["accounting", "first year", "balance sheets", "practical class", "teacher explained well", "real examples", "enjoyed numbers", "career choice"],
        band6: "The subject I want to talk about is accounting. I studied it in my first year at university. I learned about balance sheets and how companies keep records. I enjoyed it because the teacher explained with real examples and it was not only theory.",
        band65: "The subject I enjoyed most was accounting, which I studied in my first year — and I’ll admit, I expected to hate it. What changed my mind was the practicality: instead of memorising rules, we prepared a simple balance sheet for a local shop, and suddenly the logic made sense. The teacher was excellent — she used examples from shops we all knew, which made the numbers feel real. That one class probably influenced my whole career choice, because I went from tolerating accounting to genuinely finding it satisfying.",
        whyItWorks: [
          "A small honest confession ('I expected to hate it') adds personality",
          "One specific task (a balance sheet for a local shop) instead of listing course contents",
          "Includes a person and their method, which is easy fluent content",
          "Closes on a consequence for the speaker’s life — strong development",
        ],
      },
    ],
    corrections: [
      fix("“I am studying this subject from first year.”", "“I studied this subject in my first year.”", "'From' should be 'in' for a specific period here."),
      fix("“We learned many knowledges.”", "“We learned a lot.”", "'Knowledge' is uncountable; no plural form."),
      fix("“The teacher was making us understand.”", "“The teacher explained things clearly.”", "Simplify instead of translating the continuous form from Bangla."),
    ],
    practiceCards: [
      "Describe a job you would like to do.",
      "Describe a school you attended.",
      "Describe a colleague or classmate you worked well with.",
      "Describe something you learned outside the classroom.",
    ],
  }),
  cat({
    slug: "future-plans-part2",
    title: "Future plans and ambitions",
    banglaTitle: "ভবিষ্যৎ পরিকল্পনা",
    shape: "plan",
    summary: "Career plans, study plans, dreams — the only category where you need future forms and hypothetical language.",
    ideaLens: {
      label: "What?",
      prompts: [
        "What is the plan or ambition?",
        "When do you hope to do it, and why then?",
        "What do you need to do first?",
        "Who or what supports you?",
        "How do you feel about it — excited, nervous, unsure?",
      ],
    },
    storyAdvice: [
      "Use future forms deliberately: going to for plans, hope to for wishes, might/would for uncertainty.",
      "Include an obstacle. Every realistic plan has one, and describing it adds depth.",
      "Finish with how you would feel — emotions are the easiest way to extend a future cue card.",
    ],
    vocabulary: [
      v("long-term goal", "noun", "দীর্ঘমেয়াদি লক্ষ্য", "My long-term goal is to teach."),
      v("save up", "phrasal verb", "টাকা জমানো", "I’m saving up for a master’s."),
      v("apply for", "phrasal verb", "আবেদন করা", "I’ll apply for a scholarship next year."),
      v("set up", "phrasal verb", "প্রতিষ্ঠা করা", "I’d like to set up a small business."),
      v("fall back on", "phrasal verb", "সহায়ক বিকল্প রাখা", "Teaching is something I can fall back on."),
    ],
    structures: [
      { template: "In the next ___ , I’m planning to ___ .", example: "In the next two years, I’m planning to finish my degree and find an internship." },
      { template: "The main obstacle is ___ , so I ___ .", example: "The main obstacle is funding, so I’m applying for a scholarship." },
      { template: "If everything goes well, I ___ ; if not, I ___ .", example: "If everything goes well, I’ll study abroad; if not, I’ll work first and apply later." },
    ],
    cueCards: [
      {
        prompt: "Describe a plan you have for the future.",
        bullets: ["what the plan is", "when you would like to do it", "what you need to do first", "and explain how you feel about it"],
        prepNotes: ["master’s abroad", "in 2 years", "need IELTS + funding", "apply scholarship", "nervous about cost", "family supportive", "excited", "backup plan"],
        band6: "My plan for the future is to do a master’s degree abroad. I want to do it after two years. First I need to finish my degree and get a good IELTS score. I feel excited but also nervous because it is expensive.",
        band65: "In the next couple of years I’m planning to do a master’s abroad — hopefully in Malaysia or Canada, since the tuition is more manageable. Before that, though, I need to finish my degree with a decent result and get my IELTS score up to 6.5. The main obstacle is money, so I’m looking into scholarships and I’ve started saving. Honestly, I feel excited and nervous at the same time: excited because it’s something I’ve wanted for a while, nervous because if the funding doesn’t work out I’ll have to postpone it — though I’d rather work for a year and try again than give up on it.",
        whyItWorks: [
          "Specific destinations and a reason — not a vague 'abroad'",
          "Names prerequisites and a real obstacle, with a mitigation plan",
          "Uses future forms accurately: going to, need to, will have to, would rather",
          "Ends with feeling plus a fallback position — very strong development",
        ],
      },
    ],
    corrections: [
      fix("“I will go abroad in future after complete study.”", "“I’ll go abroad in the future, after I complete my studies.”", "Time expressions need 'the'; 'after' needs a clause or a noun."),
      fix("“I hope I can able to do it.”", "“I hope I’ll be able to do it.”", "Use 'will be able to', not 'can able to'."),
      fix("“My aim is go to Canada.”", "“My aim is to go to Canada.”", "'Aim' takes 'to + verb'."),
    ],
    practiceCards: [
      "Describe a job you would like to have in the future.",
      "Describe a place you would like to visit one day.",
      "Describe something you would like to buy in the future.",
      "Describe a change you would like to make in your life.",
    ],
  }),
];
