import type { Part1Topic } from "../schema";
import { fix, phrase, topic, vocab, q } from "../content-builders";

/** Second half of the Part 1 topic bank. Same schema, tighter entries —
 *  every topic still carries vocabulary, questions and Band 6 / 6.5 models. */
export const part1MoreTopics: Part1Topic[] = [
  topic({
    slug: "books",
    title: "Books",
    banglaTitle: "বই",
    summary: "Reading habits, genres and a specific book — specificity is what lifts this topic above 'I like books'.",
    tags: ["part 1", "reading", "core"],
    vocabulary: [
      vocab("fiction / non-fiction", "noun", "কল্পকাহিনি / বাস্তব", "I read mostly fiction, but I enjoy non-fiction about history."),
      vocab("gripping", "adjective", "মোহিত করা", "The first chapter was really gripping."),
      vocab("recommend", "verb", "সুপারিশ করা", "My teacher recommended it to me."),
      vocab("get through a book", "phrase", "বই শেষ করা", "I get through a book in about three weeks."),
      vocab("plot", "noun", "কাহিনির ধারা", "The plot was slow at first, then it picked up."),
    ],
    phrases: [
      phrase("I’m reading…", "আমি … পড়ছি", "I’m reading a Bengali novel at the moment."),
      phrase("What I like about it is…", "এর মধ্যে ভালো লাগে…", "What I like about it is the way the characters talk."),
      phrase("It’s not heavy reading", "বেশ হালকা পড়া", "It’s not heavy reading — good for a busy week."),
    ],
    questions: [
      q(
        "Do you like reading?",
        "পড়তে ভালো লাগে?",
        "Answer + frequency + one book detail.",
        ["Answer", "What you read", "When you read", "One specific book"],
        ["Yes, I do — I read mostly ___ , usually ___ .", "Yes, I do — I read mostly fiction, usually for half an hour before bed."],
        "Yes, I like reading. I read story books and sometimes novels. I usually read at night before sleeping, for about half an hour.",
        "Yes, though not as much as I’d like. Mostly fiction — and I’m currently halfway through a Bengali novel my teacher recommended, which turned out to be much better than the title suggested. I read at night, half an hour or so, which is the only quiet time I get.",
        [fix("I am reading book daily night.", "I read a book at night.", "Habits: present simple; 'daily night' is not English.")],
        ["read before bed", "fiction mostly", "a novel my teacher recommended"],
        ["What kind of books do you enjoy most?"],
      ),
    ],
  }),
  topic({
    slug: "reading",
    title: "Reading",
    banglaTitle: "পড়া",
    summary: "Digital vs paper, habit vs time, and how reading changed for you — comparisons do the work here.",
    tags: ["part 1", "reading", "habits"],
    vocabulary: [
      vocab("paperback", "noun", "সাধারণ বই", "I still prefer paperbacks to screens."),
      vocab("e-reader", "noun", "ই-রিডার", "I read on my phone, so an e-reader would be useful."),
      vocab("get distracted", "phrase", "মনোযোগ হারানো", "I get distracted when I read on my phone."),
      vocab("habit", "noun", "অভ্যাস", "Reading is a habit; you lose it quickly."),
      vocab("browse", "verb", "পাতা উল্টানো", "I like browsing bookshops on Fridays."),
    ],
    phrases: [
      phrase("I’ve got into the habit of…", "…-এর অভ্যাস হয়ে গেছে", "I’ve got into the habit of reading before bed."),
      phrase("Screen reading tires my eyes", "স্ক্রিনে পড়লে চোখ ক্লান্ত হয়", "Screen reading tires my eyes faster than paper."),
      phrase("It’s a way to switch off", "এটি মন হালকা করার উপায়", "It’s a way to switch off from my phone."),
    ],
    questions: [
      q(
        "Do you prefer reading on paper or on a screen?",
        "কাগজে পড়তে পছন্দ না স্ক্রিনে?",
        "Preference + reason + a concession.",
        ["Preference", "Why", "Drawback", "When you use the other"],
        ["I prefer ___ because ___ , although ___ .", "I prefer paper because I concentrate better, although I do read short articles on my phone."],
        "I prefer paper books. When I read on my phone, I get distracted by messages. But for short news I use my phone because it is quick.",
        "Paper, definitely. With a book I actually finish chapters; on my phone I end up checking messages every two minutes. The downside is cost and space, so I read short articles and news on the screen — that balance works fine for me.",
        [fix("I prefer read in paper.", "I prefer reading on paper.", "'prefer' takes -ing; use 'on paper'.")],
        ["concentrate better", "phone distracts me", "mix of both"],
        ["Do you think people read less than before?"],
      ),
    ],
  }),
  topic({
    slug: "photography",
    title: "Photography",
    banglaTitle: "ফটোগ্রাফি",
    summary: "A modern favourite. Talk about what you photograph, why, and how phones changed it.",
    tags: ["part 1", "hobbies", "technology"],
    vocabulary: [
      vocab("take a photo", "verb", "ছবি তোলা", "I take photos of everyday things."),
      vocab("capture", "verb", "ধরে রাখা (ছবিতে)", "I try to capture ordinary moments."),
      vocab("frame", "verb", "ফ্রেমে আনা", "I frame the shot before clicking."),
      vocab("edit", "verb", "সম্পাদনা করা", "I rarely edit my photos."),
      vocab("portrait", "noun", "প্রতিকৃতি", "I mostly take street photos, not portraits."),
    ],
    phrases: [
      phrase("I take photos of…", "আমি …-এর ছবি তুলি", "I take photos of streets and people, mostly."),
      phrase("It makes me notice details", "এটি খুঁটিনাটি লক্ষ্য করতে শেখায়", "It makes me notice details I’d normally walk past."),
      phrase("I’m not serious about it", "আমি খুব সিরিয়াস নই", "I’m not serious about it — it’s just something I enjoy."),
    ],
    questions: [
      q(
        "Do you like taking photographs?",
        "ছবি তুলতে ভালো লাগে?",
        "Yes/no + what you shoot + why.",
        ["Answer", "Subject", "Frequency", "Why you enjoy it"],
        ["Yes, I do — I mostly photograph ___ because ___ .", "Yes, I do — I mostly photograph streets and old buildings because they keep changing."],
        "Yes, I like photography. I take photos with my mobile phone. I usually take photos of my friends and my family.",
        "I do, though only with my phone. I mostly shoot streets and old buildings — the ones that keep getting demolished — and occasionally my cousins, who’ve given up posing. It’s less about skill and more about noticing things I’d otherwise walk past.",
        [fix("I am clicking photo always.", "I take photos quite often.", "Natural collocation is 'take a photo'; 'click' is Indian-English informal.")],
        ["phone photography", "streets and buildings", "notice the details"],
        ["Would you like to learn photography properly?"],
      ),
    ],
  }),
  topic({
    slug: "sports",
    title: "Sports",
    banglaTitle: "খেলাধুলা",
    summary: "Watching vs playing, favourite sport, and why Bangladesh's national obsession appears constantly.",
    tags: ["part 1", "sports", "core"],
    vocabulary: [
      vocab("take part in", "phrase", "অংশ নেওয়া", "I took part in a local tournament."),
      vocab("support", "verb", "সমর্থন করা", "I support the Bangladesh cricket team."),
      vocab("compete", "verb", "প্রতিযোগিতা করা", "We competed against six other schools."),
      vocab("competitive", "adjective", "প্রতিযোগিতামূলক", "Cricket here is quite competitive."),
      vocab("keep fit", "phrase", "সুস্থ থাকা", "I play for fun, mostly to keep fit."),
    ],
    phrases: [
      phrase("I’m a big fan of…", "আমি …-এর বড় ভক্ত", "I’m a big fan of cricket."),
      phrase("I play for fun, not seriously", "আমি আনন্দের জন্য খেলি", "I play for fun, not seriously."),
      phrase("We usually play in the field nearby", "আমরা সাধারণত কাছে মাঠে খেলি", "We usually play in a field nearby."),
    ],
    questions: [
      q(
        "Do you play any sports?",
        "আপনি কোনো খেলা খেলেন?",
        "Playing vs watching — be precise, then add frequency and detail.",
        ["Which sport", "How often", "Where", "Skill level"],
        ["I play ___ about ___ times a ___, usually ___ .", "I play cricket about twice a month, usually in a field near my house."],
        "I play cricket with my friends. We play on Fridays in the afternoon. I am not a very good player, but I enjoy it.",
        "Not as much as I’d like — cricket, maybe twice a month, in a field near my house. I’m honestly not a good batsman; I mostly field and talk. Still, it’s the one thing that gets me out of the house without any plan.",
        [fix("We play cricket in every Friday.", "We play cricket every Friday.", "No preposition before 'every Friday'.")],
        ["cricket with friends", "Friday afternoons", "not very good but enjoy it"],
        ["Do you prefer playing or watching sports?"],
      ),
    ],
  }),
  topic({
    slug: "exercise",
    title: "Exercise",
    banglaTitle: "ব্যায়াম",
    summary: "Fitness habits and honest answers about why we don't exercise enough.",
    tags: ["part 1", "health", "core"],
    vocabulary: [
      vocab("work out", "phrasal verb", "ব্যায়াম করা", "I work out at home, nothing fancy."),
      vocab("stay in shape", "phrase", "ফিট থাকা", "Walking helps me stay in shape."),
      vocab("jogging", "noun", "দৌড়ানো", "I go jogging three times a week."),
      vocab("warm up", "phrasal verb", "ওয়ার্ম-আপ করা", "I usually warm up for five minutes."),
      vocab("consistency", "noun", "নিয়মিততা", "Consistency matters more than intensity."),
    ],
    phrases: [
      phrase("I try to keep active", "সক্রিয় থাকার চেষ্টা করি", "I try to keep active, though not in a gym."),
      phrase("I’ve been doing it since…", "আমি এটি করছি … থেকে", "I’ve been walking every morning since January."),
      phrase("Honestly, I’m not consistent", "সত্যি বলতে, আমি নিয়মিত নই", "Honestly, I’m not consistent — exams break the habit."),
    ],
    questions: [
      q(
        "Do you do any exercise?",
        "কোনো ব্যায়াম করেন?",
        "Answer + type + frequency + honest limitation.",
        ["Type", "Frequency", "Where", "What stops you"],
        ["I mainly ___ , about ___ . I’d do more but ___ .", "I mainly walk, about half an hour a day. I’d do more but my study schedule gets in the way."],
        "Yes, I do exercise. I go for a walk in the morning for thirty minutes. Sometimes I also do some exercises at home with YouTube videos.",
        "I walk — about half an hour most mornings, and occasionally I do a short workout at home. I wouldn’t call it training, honestly; the real problem is consistency, because exam weeks break the routine and I have to start again.",
        [fix("I am going for walk daily morning.", "I go for a walk every morning.", "Habit = present simple; add articles: 'for a walk'.")],
        ["morning walks", "home workout", "breaks during exams"],
        ["Do you think exercise is important?"],
      ),
    ],
  }),
  topic({
    slug: "technology",
    title: "Technology",
    banglaTitle: "প্রযুক্তি",
    summary: "Technology at home, its benefits and the honest drawbacks — a Part 1 topic that leads straight into Part 3.",
    tags: ["part 1", "technology", "core"],
    vocabulary: [
      vocab("device", "noun", "যন্ত্র", "I mostly use two devices — a laptop and my phone."),
      vocab("save time", "phrase", "সময় বাঁচানো", "Online banking saves a lot of time."),
      vocab("rely on", "phrasal verb", "নির্ভর করা", "I rely on my phone for everything."),
      vocab("upgrade", "verb", "উন্নয়ন করা", "I upgrade my laptop only when it breaks."),
      vocab("distraction", "noun", "মনোযোগ নষ্টকারী", "Notifications are the main distraction for me."),
    ],
    phrases: [
      phrase("It’s made things much easier", "অনেক সহজ করে দিয়েছে", "Mobile banking has made things much easier."),
      phrase("The downside is…", "খারাপ দিক হলো…", "The downside is that I’m never really offline."),
      phrase("I can’t imagine life without it", "এটি ছাড়া জীবন ভাবতে পারি না", "I can’t imagine studying without it."),
    ],
    questions: [
      q(
        "What technology do you use most?",
        "সবচেয়ে বেশি কোন প্রযুক্তি ব্যবহার করেন?",
        "Name it, say what for, and add one honest drawback.",
        ["Device/tool", "Purpose", "How often", "Drawback"],
        ["Mostly ___ — I use it for ___ . The problem is ___ .", "Mostly my phone — I use it for everything from classes to payments. The problem is I never switch off."],
        "I use my mobile phone the most. I use it for study, for calling my friends and for payments. I use it almost all day.",
        "Honestly, my phone — classes, notes, payments, everything. I probably use it six or seven hours a day, which sounds worse when I say it out loud. The obvious problem is that I never properly switch off; notifications are constant.",
        [fix("I am using mobile for everything from long time.", "I’ve been using my phone for everything for a long time.", "Use present perfect continuous with 'for' + duration.")],
        ["phone for everything", "six or seven hours a day", "never switch off"],
        ["Do you think people depend too much on technology?"],
      ),
    ],
  }),
  topic({
    slug: "mobile-phones",
    title: "Mobile phones",
    banglaTitle: "মোবাইল ফোন",
    summary: "First phone, daily use and screen time — an easy topic where honest limitation questions sound natural.",
    tags: ["part 1", "technology", "core"],
    vocabulary: [
      vocab("screen time", "noun", "স্ক্রিনে কাটানো সময়", "My screen time is embarrassingly high."),
      vocab("notifications", "noun", "বিজ্ঞপ্তি", "I switched off most notifications."),
      vocab("keep in touch", "phrase", "যোগাযোগ রাখা", "It helps me keep in touch with cousins abroad."),
      vocab("battery life", "noun", "ব্যাটারির স্থায়িত্ব", "The battery life is the only issue."),
      vocab("addicted", "adjective", "আসক্ত", "I wouldn’t say addicted, but close."),
    ],
    phrases: [
      phrase("I got my first phone when…", "প্রথম ফোন পাই যখন…", "I got my first phone when I was in class nine."),
      phrase("I mainly use it for…", "মূলত ব্যবহার করি…", "I mainly use it for messaging and payments."),
      phrase("I’ve tried to cut down", "কমানোর চেষ্টা করেছি", "I’ve tried to cut down on scrolling."),
    ],
    questions: [
      q(
        "How often do you use your mobile phone?",
        "কত ঘন ঘন ফোন ব্যবহার করেন?",
        "Frequency + purpose + an honest limitation.",
        ["Frequency", "Purposes", "When you avoid it", "Drawback"],
        ["Probably ___ , mainly for ___ , though I try to ___ .", "Probably a few hours a day, mainly for messaging and payments, though I try to keep it out of reach while studying."],
        "I use my mobile phone many times a day. I use it for calling, messaging, and watching videos. I think I use it too much.",
        "More than I should — a few hours a day, split between messaging, payments and far too much scrolling. I’ve started leaving it in another room while I study, which helps, but I still check it the moment I take a break.",
        [fix("I am using mobile too much hours.", "I use my phone far too many hours.", "Use present simple, and 'too much' + noun is 'too many hours'.")],
        ["several hours a day", "messages and payments", "leave it in another room"],
        ["Would you like to reduce your phone use?"],
      ),
    ],
  }),
  topic({
    slug: "internet",
    title: "The internet",
    banglaTitle: "ইন্টারনেট",
    summary: "Study, reliability and how it changed learning — a topic that rewards cautious, balanced opinions.",
    tags: ["part 1", "technology"],
    vocabulary: [
      vocab("reliable connection", "noun", "নির্ভরযোগ্য সংযোগ", "The connection isn’t always reliable."),
      vocab("data", "noun", "ডেটা", "I run out of data by the end of the month."),
      vocab("search for", "phrasal verb", "খোঁজা", "I search for explanations when a topic is unclear."),
      vocab("at your fingertips", "phrase", "হাতের নাগালে", "Everything is at your fingertips now."),
      vocab("screen fatigue", "noun", "স্ক্রিনে ক্লান্তি", "Screen fatigue is real after long classes."),
    ],
    phrases: [
      phrase("It’s changed how I study", "পড়াশোনার ধরন বদলে দিয়েছে", "It’s changed how I study — I look things up instantly."),
      phrase("The connection can be patchy", "সংযোগ মাঝে মাঝে দুর্বল", "The connection can be patchy during the monsoon."),
      phrase("I try not to trust everything online", "অনলাইনের সব কিছু বিশ্বাস করি না", "I try not to trust everything online without checking."),
    ],
    questions: [
      q(
        "How often do you use the internet?",
        "কত ঘন ঘন ইন্টারনেট ব্যবহার করেন?",
        "Frequency + purpose + a practical detail.",
        ["Frequency", "Main uses", "Reliability", "One habit"],
        ["I’m online most of the day, mainly for ___ , although ___ .", "I’m online most of the day, mainly for classes and research, although the connection drops during heavy rain."],
        "I use the internet every day. I use it for my studies, for watching videos and for talking with friends. In my area the connection is usually good.",
        "Constantly, really — classes, research for assignments, and a fair amount of video. The connection is usually fine, though it drops during heavy rain, which always seems to happen when a deadline is close. I’ve learned to download things in advance.",
        [fix("I am using internet for my study purpose.", "I use the internet for my studies.", "'purpose' is unnecessary; 'studies' is the natural word here.")],
        ["online most of the day", "for classes and research", "drops in heavy rain"],
        ["Could you live without the internet for a week?"],
      ),
    ],
  }),
  topic({
    slug: "social-media",
    title: "Social media",
    banglaTitle: "সোশ্যাল মিডিয়া",
    summary: "Which platforms, how you use them, and the honest trade-off between connection and time.",
    tags: ["part 1", "technology", "core"],
    vocabulary: [
      vocab("scroll", "verb", "স্ক্রল করা", "I end up scrolling for an hour without noticing."),
      vocab("post", "verb", "পোস্ট করা", "I rarely post anything myself."),
      vocab("follow", "verb", "ফলো করা", "I follow a few study accounts."),
      vocab("time-consuming", "adjective", "সময়সাপেক্ষ", "It’s more time-consuming than it looks."),
      vocab("stay updated", "phrase", "আপডেট থাকা", "It keeps me updated about friends."),
    ],
    phrases: [
      phrase("I use it mostly to…", "মূলত ব্যবহার করি…", "I use it mostly to keep up with friends."),
      phrase("It can eat up your time", "সময় খেয়ে ফেলতে পারে", "It can eat up your whole evening."),
      phrase("I’ve cut down a lot", "অনেক কমিয়েছি", "I’ve cut down a lot since last year."),
    ],
    questions: [
      q(
        "Do you use social media a lot?",
        "সোশ্যাল মিডিয়া অনেক ব্যবহার করেন?",
        "Answer + platform + purpose + drawback.",
        ["Which platforms", "Purpose", "Frequency", "Effect on you"],
        ["I use ___ mainly to ___ , though it’s easy to ___ .", "I use Facebook mainly to keep up with friends, though it’s easy to lose an hour scrolling."],
        "Yes, I use social media every day. I use Facebook and YouTube. I watch videos and talk with my friends. Sometimes I waste time there.",
        "Probably more than I should — Facebook and YouTube mostly, mainly to keep in touch with cousins who live abroad. The problem is that five minutes becomes an hour without me noticing, so I’ve started deleting the apps during exam weeks.",
        [fix("I am addicted in social media.", "I’m quite addicted to social media.", "'addicted to' + noun, and avoid 'in'.")],
        ["Facebook and YouTube", "keep in touch", "wastes an hour easily"],
        ["Do you think social media is good for young people?"],
      ),
    ],
  }),
  topic({
    slug: "shopping",
    title: "Shopping",
    banglaTitle: "শপিং",
    summary: "Where you shop, online vs in person and what you buy — comparison again, with practical vocabulary.",
    tags: ["part 1", "daily life", "core"],
    vocabulary: [
      vocab("bargain", "verb", "দরদাম করা", "I usually bargain at the local market."),
      vocab("window shopping", "phrase", "শুধু দেখে ঘোরা", "I do a bit of window shopping on Fridays."),
      vocab("online order", "noun", "অনলাইন অর্ডার", "My last three orders arrived late."),
      vocab("affordable", "adjective", "সাশ্রয়ী", "It’s more affordable than the mall."),
      vocab("browse", "verb", "দেখে ঘোরা", "I browse before I decide."),
    ],
    phrases: [
      phrase("I’m not much of a shopper", "আমি খুব শপিং-প্রেমী নই", "I’m not much of a shopper, honestly."),
      phrase("I usually shop for…", "সাধারণত … কিনি", "I usually shop for clothes and books."),
      phrase("Online is convenient but…", "অনলাইন সুবিধাজনক কিন্তু…", "Online is convenient but you can’t check the quality."),
    ],
    questions: [
      q(
        "Do you like shopping?",
        "শপিং করতে ভালো লাগে?",
        "Answer honestly + where + comparison + one detail.",
        ["Answer", "Where", "Online vs market", "What you buy"],
        ["Not really / Yes — I ___ , usually for ___ , and I prefer ___ because ___ .", "Not really — I shop only when I need something, mostly clothes, and I prefer shops because I can check the fit."],
        "I like shopping a little. I usually buy clothes and books. I go to the market with my mother sometimes and also buy online.",
        "I’m not much of a shopper, to be honest — I buy things when they wear out. When I do, it’s mostly clothes, and I’d rather go to a shop than order online, mainly because sizes are unreliable and returning things is a hassle.",
        [fix("I am doing shopping in weekend.", "I go shopping at the weekend.", "'do shopping' → 'go shopping'; 'at the weekend'.")],
        ["shop only when needed", "clothes and books", "prefer trying things on"],
        ["Do you prefer shopping online or in shops?"],
      ),
    ],
  }),
  topic({
    slug: "clothes",
    title: "Clothes",
    banglaTitle: "পোশাক",
    summary: "Style, comfort, culture — talk about what you wear and why, plus traditional clothing questions.",
    tags: ["part 1", "daily life", "culture"],
    vocabulary: [
      vocab("comfortable", "adjective", "আরামদায়ক", "Comfort matters more to me than style."),
      vocab("casual", "adjective", "সাধারণ/নিত্যদিনের", "I’m usually in casual clothes."),
      vocab("formal", "adjective", "আনুষ্ঠানিক", "I only wear formal clothes for interviews."),
      vocab("traditional", "adjective", "ঐতিহ্যবাহী", "Panjabi is common for festivals."),
      vocab("go with", "phrasal verb", "মিলে যাওয়া", "This shirt goes with almost anything."),
    ],
    phrases: [
      phrase("I tend to wear…", "আমি সাধারণত পরি…", "I tend to wear simple, comfortable clothes."),
      phrase("Comfort comes first for me", "আমার কাছে আরামই আগে", "Comfort comes first for me."),
      phrase("It’s part of our culture", "এটি আমাদের সংস্কৃতির অংশ", "Wearing a panjabi at Eid is part of our culture."),
    ],
    questions: [
      q(
        "What kind of clothes do you usually wear?",
        "সাধারণত কী ধরনের পোশাক পরেন?",
        "Style + reason + comparison with formal wear.",
        ["Style", "Colours", "Why", "When you change"],
        ["I usually wear ___ , because ___ . I only ___ when ___ .", "I usually wear casual clothes, because they’re comfortable. I only dress formally for interviews."],
        "I usually wear casual clothes like jeans and a t-shirt. I like light colours. When I go to a function, I wear a panjabi.",
        "Mostly casual — jeans, a shirt, and comfortable shoes. It’s partly about comfort and partly because I don’t like deciding what to wear. For festivals or family functions, though, I do enjoy wearing a panjabi; it feels like an occasion.",
        [fix("I am wearing shirt and pant.", "I wear a shirt and trousers.", "'pant' should be 'trousers' in British English; habits use present simple.")],
        ["casual clothes", "light colours", "panjabi for festivals"],
        ["Do you wear traditional clothes often?"],
      ),
    ],
  }),
  topic({
    slug: "transport",
    title: "Transport",
    banglaTitle: "যাতায়াত",
    summary: "How you travel, what it costs you and comparisons between options — very common in Part 1 and Part 3.",
    tags: ["part 1", "daily life", "core"],
    vocabulary: [
      vocab("public transport", "noun", "গণপরিবহন", "Public transport here is cheap but crowded."),
      vocab("traffic jam", "noun", "জ্যাম", "I got stuck in a traffic jam for an hour."),
      vocab("commute", "verb", "যাওয়া-আসা করা", "I commute by bus every day."),
      vocab("fare", "noun", "ভাড়া", "The fare went up again last month."),
      vocab("convenient", "adjective", "সুবিধাজনক", "Buses are cheaper but less convenient."),
    ],
    phrases: [
      phrase("I usually get around by…", "সাধারণত … দিয়ে যাতায়াত করি", "I usually get around by bus or rickshaw."),
      phrase("It takes me about…", "আমার প্রায় … লাগে", "It takes me about forty minutes each way."),
      phrase("The traffic is the real problem", "আসল সমস্যা জ্যাম", "The traffic is the real problem, not the distance."),
    ],
    questions: [
      q(
        "How do you usually travel around your city?",
        "শহরে সাধারণত কীভাবে যাতায়াত করেন?",
        "Mode + time + comparison + one frustration.",
        ["Mode", "Time taken", "Cost", "Alternative you use"],
        ["I usually ___ , which takes about ___ , though sometimes I ___ .", "I usually take the bus, which takes about forty minutes, though sometimes I take a rickshaw when I’m late."],
        "I usually travel by bus. It takes about thirty minutes to go to my university. Sometimes I use rickshaw if I am late. The bus is cheap.",
        "Mostly the bus — around forty minutes each way, depending on the traffic. It’s cheap, which matters, but it’s slow during office hours. If I’m running late I take a rickshaw for part of the journey, which costs more but saves time.",
        [fix("I am going by bus daily.", "I go by bus every day.", "Habits = present simple; 'daily' sounds formal as an adverb here.")],
        ["bus most days", "forty minutes each way", "rickshaw when late"],
        ["Would you prefer to drive your own car?"],
      ),
    ],
  }),
  topic({
    slug: "travel",
    title: "Travel",
    banglaTitle: "ভ্রমণ",
    summary: "Trips you have taken and places you want to go — past tense plus future plans in one topic.",
    tags: ["part 1", "travel", "core"],
    vocabulary: [
      vocab("short break", "noun", "ছোট ছুটি", "We took a short break in Cox’s Bazar."),
      vocab("sightseeing", "noun", "দর্শনীয় স্থান দেখা", "We spent two days sightseeing."),
      vocab("off the beaten track", "phrase", "অচেনা জায়গা", "I’d like to go somewhere off the beaten track."),
      vocab("itinerary", "noun", "ভ্রমণসূচি", "We didn’t really plan an itinerary."),
      vocab("budget-friendly", "adjective", "বাজেট-বান্ধব", "It’s a budget-friendly option."),
    ],
    phrases: [
      phrase("I’ve been to…", "আমি … গিয়েছি", "I’ve been to Sylhet a couple of times."),
      phrase("What I enjoyed most was…", "সবচেয়ে বেশি ভালো লেগেছিল…", "What I enjoyed most was the train journey."),
      phrase("I’d love to visit…", "আমি … যেতে চাই", "I’d love to visit Nepal at some point."),
    ],
    questions: [
      q(
        "Do you like travelling?",
        "ভ্রমণ করতে ভালো লাগে?",
        "Answer + one trip + reason + future plan.",
        ["Answer", "A trip you took", "Why you enjoy it", "Where you want to go"],
        ["I do — I’ve been to ___ , and what I liked most was ___ . I’d love to ___ .", "I do — I’ve been to Sylhet twice, and what I liked most was how unhurried everything felt."],
        "Yes, I like travelling very much. I have visited Cox’s Bazar and Sylhet. I like seeing new places and eating different food. I want to visit Nepal in the future.",
        "I do, though I haven’t travelled nearly as much as I’d like — mostly Cox’s Bazar and Sylhet. What I enjoy is the change of routine: no timetable for a few days, and unfamiliar food. Eventually I’d like to travel outside Bangladesh, maybe Nepal or Thailand.",
        [fix("I have visited many countries like Cox’s Bazar.", "I’ve visited several places in Bangladesh, such as Cox’s Bazar.", "'like' should be 'such as'; and Cox’s Bazar is a city, not a country.")],
        ["short trips", "change of routine", "want to travel abroad"],
        ["Do you prefer travelling alone or with others?"],
      ),
    ],
  }),
  topic({
    slug: "holidays",
    title: "Holidays",
    banglaTitle: "ছুটি",
    summary: "Long breaks, festivals and how you spend your time off — a natural bridge into Part 3 about work–life balance.",
    tags: ["part 1", "routine", "culture"],
    vocabulary: [
      vocab("time off", "noun", "ছুটি", "I get about two weeks off a year."),
      vocab("recharge", "verb", "শক্তি ফিরে পাওয়া", "Holidays give me a chance to recharge."),
      vocab("family gathering", "noun", "পারিবারিক মিলন", "Eid means a big family gathering."),
      vocab("get away", "phrasal verb", "কোথাও চলে যাওয়া", "We try to get away for a few days."),
      vocab("unwind", "verb", "মন হালকা করা", "I unwind by doing nothing at all."),
    ],
    phrases: [
      phrase("During the holidays, I usually…", "ছুটিতে সাধারণত…", "During the holidays, I usually visit relatives."),
      phrase("It gives me time to…", "এতে সময় পাই…", "It gives me time to catch up on sleep."),
      phrase("I’d rather stay home than…", "…-এর চেয়ে ঘরে থাকা ভালো", "I’d rather stay home than travel during Eid traffic."),
    ],
    questions: [
      q(
        "What do you usually do on public holidays?",
        "সরকারি ছুটির দিনে সাধারণত কী করেন?",
        "Routine + one specific holiday + why it matters.",
        ["Typical activity", "With whom", "Which holiday", "Why it matters"],
        ["On holidays I usually ___ . The one I look forward to is ___ because ___ .", "On holidays I usually stay at home and rest. The one I look forward to most is Eid, because the whole family gathers."],
        "On public holidays, I usually stay at home and rest. I also help my mother in the house. Sometimes we go to my grandmother’s house in the village.",
        "Honestly, my favourite kind of holiday involves doing very little — sleeping properly, and catching up on whatever I’ve been putting off. Eid is the exception; that’s when the whole extended family gathers, and it’s noisy in a way I actually look forward to.",
        [fix("In holiday I am sleeping all day.", "On holidays I sleep a lot.", "Use 'on holidays'; avoid overstatement like 'all day'.")],
        ["rest and sleep", "Eid family gathering", "visit grandmother"],
        ["Do you think holidays are too short?"],
      ),
    ],
  }),
  topic({
    slug: "festivals",
    title: "Festivals",
    banglaTitle: "উৎসব",
    summary: "Cultural celebration questions appear constantly. Learn to describe a festival's atmosphere, not just its name.",
    tags: ["part 1", "culture", "core"],
    vocabulary: [
      vocab("celebrate", "verb", "উদযাপন করা", "We celebrate Eid with the whole family."),
      vocab("atmosphere", "noun", "পরিবেশ", "The atmosphere in the market is electric."),
      vocab("tradition", "noun", "ঐতিহ্য", "Exchanging sweets is a tradition here."),
      vocab("procession", "noun", "শোভাযাত্রা", "There’s a procession on the last day."),
      vocab("decorate", "verb", "সাজানো", "People decorate their houses with lights."),
    ],
    phrases: [
      phrase("The whole city comes alive", "পুরো শহর প্রাণবন্ত হয়ে ওঠে", "During Eid the whole city comes alive."),
      phrase("It’s a family occasion for us", "এটি আমাদের পারিবারিক অনুষ্ঠান", "Pohela Boishakh is a family occasion for us."),
      phrase("What I enjoy most is…", "সবচেয়ে ভালো লাগে…", "What I enjoy most is the food, obviously."),
    ],
    questions: [
      q(
        "What is your favourite festival?",
        "আপনার প্রিয় উৎসব কোনটি?",
        "Name it + when + what happens + why you like it.",
        ["Festival", "When", "What you do", "Why you like it"],
        ["My favourite is ___ , which happens in ___ . What I like most is ___ .", "My favourite is Eid, which happens twice a year. What I like most is seeing all my cousins in one place."],
        "My favourite festival is Eid. It comes two times in a year. We wear new clothes, go to the mosque, and eat special food with family. I like it because all my cousins come.",
        "Eid, without a doubt — mainly for the family side rather than the religious part alone. Everyone comes home, we eat far too much, and for a couple of days nobody is rushing anywhere. Pohela Boishakh is a close second because of the food stalls.",
        [fix("We celebrate Eid with much enjoy.", "We celebrate Eid with a lot of enjoyment.", "'enjoyment' is the noun; 'enjoy' is a verb.")],
        ["Eid with the family", "new clothes", "special food"],
        ["How do people celebrate it in your area?"],
      ),
    ],
  }),
  topic({
    slug: "gifts",
    title: "Gifts",
    banglaTitle: "উপহার",
    summary: "Giving and receiving: occasions, thoughtful choices and one specific memory.",
    tags: ["part 1", "people", "memory"],
    vocabulary: [
      vocab("thoughtful", "adjective", "ভেবেচিন্তে দেওয়া", "It was a thoughtful gift."),
      vocab("occasion", "noun", "উপলক্ষ", "Weddings are the main occasion for gifts."),
      vocab("handmade", "adjective", "হাতে তৈরি", "She prefers handmade things."),
      vocab("surprise", "verb", "অবাক করা", "I surprised my mother with a phone."),
      vocab("reciprocate", "verb", "কিছুর বদলে কিছু দেওয়া", "I gave him something to reciprocate."),
    ],
    phrases: [
      phrase("The best gift I received was…", "সেরা উপহার ছিল…", "The best gift I received was a bicycle from my uncle."),
      phrase("It’s the thought that counts", "ভালোবাসাই বড় কথা", "It’s the thought that counts, not the price."),
      phrase("I prefer giving…", "আমি দিতে বেশি পছন্দ করি…", "I prefer giving books, because they last."),
    ],
    questions: [
      q(
        "Do you like giving gifts?",
        "উপহার দিতে ভালো লাগে?",
        "Answer + what you give + why + one example.",
        ["Answer", "What you give", "Occasions", "A specific example"],
        ["Yes, I do — I usually give ___ , because ___ .", "Yes, I do — I usually give books or food, because they’re useful and I’m terrible at choosing clothes."],
        "Yes, I like giving gifts. I usually give clothes or books to my family on birthdays and Eid. Last year I gave my mother a scarf.",
        "I do, though I’m not great at it — my instinct is always books or something edible, because at least it gets used. Last Eid I gave my uncle a set of novels, and he actually read them, which surprised everyone including me.",
        [fix("I gave my mother a gift which is very much nice.", "I gave my mother a really nice gift.", "'which is very much nice' is unnatural; simplify.")],
        ["books and food", "birthdays and Eid", "poor at choosing clothes"],
        ["What is the best gift you have received?"],
      ),
    ],
  }),
  topic({
    slug: "birthdays",
    title: "Birthdays",
    banglaTitle: "জন্মদিন",
    summary: "A warm, easy topic — memories, traditions and how celebrations changed as you grew up.",
    tags: ["part 1", "people", "memory"],
    vocabulary: [
      vocab("celebrate", "verb", "উদযাপন করা", "We usually celebrate at home."),
      vocab("treat", "verb", "খাওয়ানো/উপহার", "My sister treats us on her birthday."),
      vocab("gathering", "noun", "সমাবেশ", "We had a small family gathering."),
      vocab("candle", "noun", "মোমবাতি", "I haven’t blown out candles in years."),
      vocab("memorable", "adjective", "স্মরণীয়", "It was a memorable evening."),
    ],
    phrases: [
      phrase("We usually celebrate at home", "সাধারণত বাড়িতে উদযাপন করি", "We usually celebrate at home with cake."),
      phrase("As I got older, …", "বড় হওয়ার সাথে সাথে…", "As I got older, birthdays became quieter."),
      phrase("The best memory is…", "সেরা স্মৃতি…", "The best memory is my tenth birthday."),
    ],
    questions: [
      q(
        "How do you usually celebrate your birthday?",
        "জন্মদিন সাধারণত কীভাবে উদযাপন করেন?",
        "Routine + change over time + a specific memory.",
        ["What you do", "Who with", "How it changed", "One memory"],
        ["These days I ___ , though when I was younger I ___ .", "These days I just have dinner with family, though when I was younger I used to invite half the class."],
        "Usually I celebrate my birthday at home. My mother cooks special food and we cut a cake in the evening. Sometimes my friends come to my house.",
        "It’s fairly quiet now — family dinner, maybe cake if someone remembers to buy it. When I was a child, though, birthdays were a big production: streamers, invitations, and a group photo. I actually miss that a bit.",
        [fix("I am celebrating my birthday with friends every year.", "I celebrate my birthday with friends every year.", "Habit = present simple.")],
        ["family dinner", "cake in the evening", "used to invite friends"],
        ["What was your best birthday?"],
      ),
    ],
  }),
  topic({
    slug: "animals",
    title: "Animals",
    banglaTitle: "প্রাণী",
    summary: "Pets, wildlife and the cow you see every day — vocabulary is easy here; development is what matters.",
    tags: ["part 1", "nature"],
    vocabulary: [
      vocab("pets", "noun", "পোষা প্রাণী", "We don’t have any pets at home."),
      vocab("stray", "adjective", "এলোমেলো/রাস্তার", "There are a lot of stray dogs nearby."),
      vocab("wildlife", "noun", "বন্যপ্রাণী", "The Sundarbans has amazing wildlife."),
      vocab("loyal", "adjective", "বিশ্বস্ত", "Dogs are famously loyal."),
      vocab("take care of", "phrase", "যত্ন নেওয়া", "My cousin takes care of three cats."),
    ],
    phrases: [
      phrase("I’m quite fond of…", "আমি … ভালোবাসি", "I’m quite fond of cats, actually."),
      phrase("We don’t keep any pets, but…", "আমরা পোষা প্রাণী রাখি না, তবে…", "We don’t keep pets, but my uncle has a cow."),
      phrase("What I like about them is…", "তাদের সম্পর্কে ভালো লাগে…", "What I like about dogs is how they react when you come home."),
    ],
    questions: [
      q(
        "Do you have any pets?",
        "পোষা প্রাণী আছে?",
        "Answer + detail + honest reason if the answer is no.",
        ["Answer", "Animal", "Who looks after it", "Why/why not"],
        ["We don’t have pets, mainly because ___ , although ___.", "We don’t have pets, mainly because our flat is small, although my cousin has two cats."],
        "No, I don’t have any pets. My uncle has a cow in the village. I like cats, but my mother doesn’t want animals in the house.",
        "Not at the moment — our flat is small, and my mother is firmly against it. My cousin keeps two cats, though, and I look after them whenever she travels. Honestly, they’ve converted me; I’d probably get one when I have my own place.",
        [fix("I don’t have any pet, but my friend have a dog.", "I don’t have any pets, but my friend has a dog.", "Plural 'pets'; third person 'has'.")],
        ["no pets at home", "cousin has cats", "would like one later"],
        ["What animals are common in your area?"],
      ),
    ],
  }),
  topic({
    slug: "parks",
    title: "Parks",
    banglaTitle: "পার্ক",
    summary: "Public spaces: what people do there, why cities need them, and your own visits.",
    tags: ["part 1", "places", "city life"],
    vocabulary: [
      vocab("green space", "noun", "সবুজ জায়গা", "Cities need more green space."),
      vocab("jogging track", "noun", "দৌড়ানোর পথ", "There’s a jogging track around the lake."),
      vocab("picnic spot", "noun", "পিকনিকের জায়গা", "Families treat it as a picnic spot."),
      vocab("well-maintained", "adjective", "ভালোভাবে রক্ষণাবেক্ষণ করা", "The park is surprisingly well-maintained."),
      vocab("get away from the crowd", "phrase", "ভিড় থেকে দূরে যাওয়া", "I go there to get away from the crowd."),
    ],
    phrases: [
      phrase("There’s a park near my house", "আমার বাড়ির কাছে একটি পার্ক আছে", "There’s a park near my house where I walk."),
      phrase("People go there to…", "মানুষ সেখানে যায়…", "People go there to walk and to meet friends."),
      phrase("It’s a break from the traffic", "জাম থেকে বিরতি", "It’s a break from the traffic and the noise."),
    ],
    questions: [
      q(
        "Do you often visit parks?",
        "প্রায়ই পার্কে যান?",
        "Frequency + purpose + description + why it matters.",
        ["How often", "What you do", "Who with", "Why you go"],
        ["I go about ___ , usually to ___ . It’s nice because ___ .", "I go about twice a week, usually to walk, because it’s the only quiet place nearby."],
        "I visit a park near my house sometimes, maybe once a week. I go with my friend. We walk and talk there. It is good for taking fresh air.",
        "Not as often as I should — maybe twice a week, usually in the evening. There’s a small lake and a walking path, and it’s surprisingly calm given how close the main road is. It’s the only place nearby where I can walk without dodging traffic.",
        [fix("I am going to park for take fresh air.", "I go to the park to get some fresh air.", "Purpose: 'to + verb'; 'take fresh air' is not natural English.")],
        ["twice a week", "walk by the lake", "fresh air and quiet"],
        ["Why do people need parks in cities?"],
      ),
    ],
  }),
  topic({
    slug: "teachers",
    title: "Teachers",
    banglaTitle: "শিক্ষক",
    summary: "Describe a teacher who mattered — personality, method and one concrete memory.",
    tags: ["part 1", "people", "education"],
    vocabulary: [
      vocab("inspiring", "adjective", "অনুপ্রেরণাদায়ী", "Our English teacher was genuinely inspiring."),
      vocab("patient", "adjective", "ধৈর্যশীল", "She was incredibly patient with us."),
      vocab("encourage", "verb", "উৎসাহ দেওয়া", "He encouraged me to speak up."),
      vocab("approachable", "adjective", "কাছে যাওয়ার মতো", "She was approachable, so we asked questions."),
      vocab("strict but fair", "phrase", "কঠোর তবে ন্যায্য", "He was strict but fair."),
    ],
    phrases: [
      phrase("I had a teacher who…", "আমার একজন শিক্ষক ছিলেন যিনি…", "I had a teacher who made grammar interesting."),
      phrase("What made them special was…", "তাকে বিশেষ করে তুলেছিল…", "What made her special was how she treated us."),
      phrase("They changed how I…", "তিনি বদলে দিয়েছিলেন আমার…", "He changed how I felt about studying."),
    ],
    questions: [
      q(
        "Do you have a favourite teacher?",
        "প্রিয় শিক্ষক আছেন?",
        "Who + subject + personality + one memory.",
        ["Who", "Subject", "Personality", "One memory"],
        ["Yes — my ___ teacher, who was ___ . I still remember ___ .", "Yes — my English teacher in school, who was incredibly patient. I still remember how she repeated things without ever sounding annoyed."],
        "Yes, my favourite teacher was my English teacher in school. She was very friendly and patient. She helped me when I could not understand grammar. I still remember her classes.",
        "Definitely — my English teacher in class nine. She had this way of explaining grammar that didn’t feel like rules; she’d use our own sentences as examples, which was slightly embarrassing and very effective. She was strict about homework but never made anyone feel stupid, and that’s rarer than it should be.",
        [fix("She was very much helpful for me.", "She was very helpful to me.", "Use 'helpful to' and avoid 'very much' with adjectives.")],
        ["English teacher", "patient and friendly", "explained clearly"],
        ["What makes a good teacher?"],
      ),
    ],
  }),
  topic({
    slug: "childhood",
    title: "Childhood",
    banglaTitle: "শৈশব",
    summary: "Past-tense storytelling at its easiest: games, habits, and 'used to' structures.",
    tags: ["part 1", "memory", "past"],
    vocabulary: [
      vocab("used to", "phrase", "অভ্যস্ত ছিল", "I used to play cricket every afternoon."),
      vocab("neighbourhood", "noun", "পাড়া", "The whole neighbourhood knew each other."),
      vocab("carefree", "adjective", "নির্ভাবন", "Childhood felt carefree."),
      vocab("make-believe", "noun", "কল্পনার খেলা", "We played make-believe games for hours."),
      vocab("grow up", "verb", "বড় হওয়া", "I grew up in a small town."),
    ],
    phrases: [
      phrase("When I was a child, I used to…", "ছোটবেলায় আমি … করতাম", "When I was a child, I used to climb trees."),
      phrase("Looking back, …", "পিছনে তাকালে…", "Looking back, we had very little and it didn’t matter."),
      phrase("We spent hours doing…", "আমরা ঘণ্টার পর ঘণ্টা … করতাম", "We spent hours playing in the field."),
    ],
    questions: [
      q(
        "What did you enjoy doing as a child?",
        "শিশু হিসেবে কী করতে ভালো লাগত?",
        "Past routine with 'used to' + one vivid memory.",
        ["Activity", "Where", "Who with", "One memory"],
        ["When I was a child, I used to ___ , and I remember ___ .", "When I was a child, I used to play cricket every afternoon, and I remember one match that went on until dark."],
        "When I was a child, I liked playing cricket with my friends. We played in a field near our house. I also liked watching cartoons in the afternoon.",
        "Mostly cricket — every afternoon in the field behind our house, with a wicket drawn on a wall. I also had a phase of collecting stickers, which I’d completely forgotten about until now. Looking back, the best part was that nobody had a schedule.",
        [fix("I was playing cricket every afternoon in my childhood.", "I used to play cricket every afternoon when I was a child.", "Past habits use 'used to', not past continuous.")],
        ["play cricket", "in the field", "until it got dark"],
        ["Do you think childhood is different now?"],
      ),
    ],
  }),
  topic({
    slug: "future-plans",
    title: "Future plans",
    banglaTitle: "ভবিষ্যৎ পরিকল্পনা",
    summary: "Future forms in the wild: going to, hope to, plan to — plus a realistic reason for each plan.",
    tags: ["part 1", "future", "core"],
    vocabulary: [
      vocab("plan to", "phrase", "পরিকল্পনা করা", "I plan to apply for a master’s next year."),
      vocab("hope to", "phrase", "আশা করা", "I hope to work abroad for a few years."),
      vocab("career", "noun", "পেশা", "I want a career in finance."),
      vocab("settle down", "phrasal verb", "স্থিত হওয়া", "I’d like to settle down near my parents."),
      vocab("long-term", "adjective", "দীর্ঘমেয়াদি", "My long-term goal is to teach."),
    ],
    phrases: [
      phrase("In the next few years, I’m going to…", "আগামী কয়েক বছরে আমি…", "In the next few years, I’m going to finish my degree."),
      phrase("Eventually, I’d like to…", "শেষ পর্যন্ত আমি … চাই", "Eventually, I’d like to run my own business."),
      phrase("I haven’t decided yet, but…", "এখনো ঠিক করিনি, তবে…", "I haven’t decided yet, but teaching appeals to me."),
    ],
    questions: [
      q(
        "What are your plans for the future?",
        "ভবিষ্যতের পরিকল্পনা কী?",
        "Two or three plans with reasons, using future forms.",
        ["Short-term", "Long-term", "Why", "Uncertainty"],
        ["In the short term, I’m going to ___ . Later, I hope to ___ , mainly because ___ .", "In the short term, I’m going to finish my degree. Later, I hope to work in a bank, mainly because it’s stable."],
        "In the future, I want to complete my studies and get a good job. I want to work in a bank. After that, maybe I will do a master’s degree abroad.",
        "Short term, I’m going to finish my degree and try to get an internship — ideally in a bank, since that’s the field I’ve trained for. Longer term, I’d like to do a master’s abroad, though that depends on funding. Honestly, I’m not completely decided yet, and I think that’s normal at my age.",
        [fix("I will finish my study and I will get a job, then I will do marriage.", "I’ll finish my studies and get a job, and then hopefully get married.", "Plural 'studies'; 'do marriage' is not English.")],
        ["finish my degree", "work in a bank", "master’s abroad"],
        ["Would you like to live abroad?"],
      ),
    ],
  }),
  topic({
    slug: "names",
    title: "Names",
    banglaTitle: "নাম",
    summary: "The classic opener: your name, its meaning and whether you like it. Short answers are tempting here — resist.",
    tags: ["part 1", "basics", "core"],
    vocabulary: [
      vocab("given name", "noun", "প্রদত্ত নাম", "My given name means 'light'."),
      vocab("nickname", "noun", "ডাকনাম", "My family uses a nickname at home."),
      vocab("meaning", "noun", "অর্থ", "The meaning is connected to my grandmother."),
      vocab("common", "adjective", "সাধারণ", "It’s a fairly common name in Bangladesh."),
      vocab("stand out", "phrasal verb", "আলাদা হওয়া", "I like that my name stands out a little."),
    ],
    phrases: [
      phrase("My name is…, which means…", "আমার নাম …, যার অর্থ…", "My name is Rafi, which means 'kind'."),
      phrase("It’s quite common here", "এখানে এটি বেশ সাধারণ", "It’s quite common here — I know three others."),
      phrase("I’m happy with it", "আমি খুশি", "I’m happy with it, though people often misspell it."),
    ],
    questions: [
      q(
        "Does your name have a special meaning?",
        "আপনার নামের কোনো বিশেষ অর্থ আছে?",
        "Meaning + source + how you feel about it.",
        ["Meaning", "Where it comes from", "Family connection", "Your feeling"],
        ["My name means ___ , and it comes from ___ . I like it because ___ .", "My name means 'light', and it comes from Arabic. I like it because it’s easy to pronounce."],
        "My name means light. It is from Arabic. My parents chose it because they liked the meaning. I like my name very much.",
        "It does — it means something close to 'light' in Arabic, and my grandmother chose it, which is why I’ve never really considered changing it. It’s a fairly common name in Bangladesh, though, so there are three people with the same name in my class.",
        [fix("My name has a good meaning which is given by my grand mother.", "My name has a nice meaning, and my grandmother chose it.", "Avoid overuse of 'which'; 'grandmother' is one word.")],
        ["means 'light'", "chosen by my grandmother", "quite common"],
        ["Would you like to change your name?"],
      ),
    ],
  }),
];
