/**
 * The mistake library.
 *
 * One searchable collection for the eight error families Bangladeshi learners
 * hit most often. Every entry follows the same teaching shape:
 *   ❌ what learners say → ✅ what sounds natural → why it matters → Bangla note
 *
 * Entries that carry a `detect` regex double as the rule set used by the
 * speaking evaluator in `src/lib/practice/evaluate.ts`, so a detected problem
 * in practice always links back to a searchable explanation here.
 */
import type { MistakeEntry } from "./schema";
import { mist } from "./content-builders";

export const mistakes: MistakeEntry[] = [
  /* ------------------------------------------------------------------ */
  /* Grammar                                                             */
  /* ------------------------------------------------------------------ */
  mist(
    "grammar-been-since",
    "grammar",
    "Tense — present perfect",
    "I am living in Dhaka since 2019.",
    "I have been living in Dhaka since 2019.",
    "A situation that started in the past and continues now takes the present perfect, not the present continuous.",
    "বাংলায় 'আমি ২০১৯ থেকে ঢাকায় থাকি' — এখানে ক্রিয়া বর্তমান কালেও চলছে, তাই ইংরেজিতে 'have been living' হয়।",
    "very-common",
    [{ wrong: "I know him since school.", right: "I've known him since school." }],
    "\\b(am|is|are) (living|working|studying|staying|doing)\\b[^.]{0,40}\\bsince\\b",
  ),
  mist(
    "grammar-for-since",
    "grammar",
    "Tense — for / since",
    "I am working here from two years.",
    "I've been working here for two years.",
    "Use 'for' with a length of time and 'since' with a starting point. Present perfect continuous shows the activity is still going.",
    "'Two years' মানে সময়ের পরিমাণ — তাই 'for'. '2021' বা 'last April' মানে শুরুর বিন্দু — তাই 'since'.",
    "very-common",
    [{ wrong: "He is in London since January.", right: "He's been in London since January." }],
    "\\b(from|since)\\s+(one|two|three|four|five|ten|\\d+)\\s+(day|week|month|year)s?\\b",
  ),
  mist(
    "grammar-didnt-past",
    "grammar",
    "Tense — past simple",
    "I didn't went to the market yesterday.",
    "I didn't go to the market yesterday.",
    "After 'did / didn't', the verb stays in its base form because the past is already marked by 'did'.",
    "'did' নিজেই অতীত বোঝায়, তাই এর পরের ক্রিয়া base form-এ থাকে — 'went' নয়, 'go'।",
    "very-common",
    [{ wrong: "She didn't came to the class.", right: "She didn't come to the class." }],
    "\\bdidn'?t\\s+(went|came|took|made|saw|got|had|was|were|did|said|told|knew|gave|found)\\b",
  ),
  mist(
    "grammar-subject-verb-agreement",
    "grammar",
    "Subject–verb agreement",
    "My brother go to university every day.",
    "My brother goes to university every day.",
    "Third-person singular subjects take -s in the present simple.",
    "একবচন তৃতীয় পুরুষের (he, she, my brother) ক্রিয়ার শেষে -s যোগ হয়।",
    "very-common",
    [{ wrong: "People goes there.", right: "People go there." }],
    "\\b(my (brother|sister|father|mother|friend|cousin|teacher)|he|she|it)\\s+(go|come|like|want|live|study|work|make|take|play)\\b",
  ),
  mist(
    "grammar-people-is",
    "grammar",
    "Subject–verb agreement",
    "People is very friendly in my area.",
    "People are very friendly in my area.",
    "'People' is already plural and takes a plural verb. Its singular is 'person'.",
    "'People' শব্দটি বহুবচন — তাই 'are' বসে। একবচনে 'a person is'।",
    "very-common",
    [{ wrong: "Many people was there.", right: "Many people were there." }],
    "\\bpeople\\s+(is|was|has|does)\\b",
  ),
  mist(
    "grammar-articles-missing",
    "grammar",
    "Articles",
    "I want to be engineer.",
    "I want to be an engineer.",
    "Singular countable nouns need an article. 'An' goes before a vowel sound.",
    "একবচন গণনাযোগ্য বিশেষ্যের আগে a / an / the লাগে — 'engineer'-এর আগে vowel sound, তাই 'an'।",
    "very-common",
    [{ wrong: "She is teacher.", right: "She's a teacher." }],
    "\\b(am|is|are|want to be|will be)\\s+(engineer|teacher|doctor|student|nurse|manager|driver|farmer)\\b",
  ),
  mist(
    "grammar-articles-the",
    "grammar",
    "Articles",
    "I go to the university by the bus every day.",
    "I go to university by bus every day.",
    "Fixed expressions drop 'the': by bus, at home, to school, in bed, at work.",
    "কিছু নির্দিষ্ট বাক্যাংশে 'the' বসে না — by bus, at home, to school, in bed।",
    "common",
    [{ wrong: "He is at the home now.", right: "He's at home now." }],
    "\\bby the (bus|train|car|rickshaw|bike|plane)\\b|\\bat the home\\b",
  ),
  mist(
    "grammar-preposition-in-on",
    "grammar",
    "Prepositions",
    "I am studying in University of Dhaka.",
    "I'm studying at the University of Dhaka.",
    "Use 'at' for institutions and places where something happens, and 'in' for cities and countries.",
    "প্রতিষ্ঠানের নামের আগে সাধারণত 'at' বসে, শহর বা দেশের আগে 'in'।",
    "common",
    [{ wrong: "I work in a bank in Motijheel.", right: "I work at a bank in Motijheel." }],
    "\\bstudying in (the )?(University|College|School|BUET)\\b",
  ),
  mist(
    "grammar-discuss-about",
    "grammar",
    "Prepositions — verbs",
    "We discussed about the problem.",
    "We discussed the problem.",
    "'Discuss' takes a direct object — no preposition.",
    "'Discuss' ক্রিয়ার পর সরাসরি object বসে, 'about' লাগে না।",
    "common",
    [{ wrong: "They discussed about their plans.", right: "They discussed their plans." }],
    "\\bdiscuss(ed|ing)?\\s+about\\b",
  ),
  mist(
    "grammar-reach-to",
    "grammar",
    "Prepositions — verbs",
    "We reached to Cox's Bazar at night.",
    "We reached Cox's Bazar at night.",
    "'Reach' is transitive and takes no preposition.",
    "'Reach' এর পর 'to' বসে না; 'arrive in / at' হলে preposition লাগে।",
    "very-common",
    [{ wrong: "I will reach to the office by 9.", right: "I'll reach the office by 9." }],
    "\\breach(ed)?\\s+to\\b",
  ),
  mist(
    "grammar-married-with",
    "grammar",
    "Collocation — preposition",
    "She is married with a doctor.",
    "She's married to a doctor.",
    "The fixed collocation is 'married to' someone.",
    "'married to' — এটাই নির্দিষ্ট রূপ; 'with' নয়।",
    "common",
    undefined,
    "\\bmarried\\s+with\\b",
  ),
  mist(
    "grammar-much-many",
    "grammar",
    "Quantifiers",
    "I have many informations about this topic.",
    "I have quite a lot of information about this topic.",
    "'Information' is uncountable — no plural, and 'many' does not fit.",
    "'Information', 'advice', 'knowledge', 'furniture' — এগুলো অগণনীয়; plural হয় না।",
    "very-common",
    [{ wrong: "He gave me many advices.", right: "He gave me a lot of advice." }],
    "\\bmany\\s+(information|advice|knowledge|furniture|homework|equipment)\\b",
  ),
  mist(
    "grammar-very-much",
    "grammar",
    "Adverb + adjective",
    "The food was very much delicious.",
    "The food was absolutely delicious.",
    "'Very much' does not modify adjectives; use 'very', 'really' or 'absolutely'.",
    "বিশেষণের আগে 'very much' বসে না — 'very' বা 'really' বসে। 'very much' বস্তুর সঙ্গে ক্রিয়ার পরে বসে: I liked it very much.",
    "very-common",
    [{ wrong: "It was very much difficult.", right: "It was really difficult." }],
    "\\bvery much (good|nice|beautiful|delicious|difficult|happy|tired|excited|important|big|small)\\b",
  ),
  mist(
    "grammar-comparative-double",
    "grammar",
    "Comparatives",
    "Dhaka is more bigger than my town.",
    "Dhaka is much bigger than my town.",
    "Use either '-er' or 'more', never both. Use 'much' or 'far' to strengthen.",
    "বড় করার জন্য 'much bigger' বা 'far bigger' বলুন, 'more bigger' কখনও নয়।",
    "very-common",
    [{ wrong: "This is more easier than that.", right: "This is much easier than that." }],
    "\\bmore\\s+(bigger|better|easier|happier|cheaper|older|younger|faster|stronger|nicer|busier|worse|higher|larger)\\b",
  ),
  mist(
    "grammar-am-agree",
    "grammar",
    "Verb form — 'agree'",
    "I am agree with this idea.",
    "I agree with this idea.",
    "'Agree' is a verb, so it never follows 'am / is / are'.",
    "'agree' নিজেই ক্রিয়া — এর সঙ্গে am/is/are বসে না।",
    "very-common",
    [{ wrong: "I am fully agree.", right: "I completely agree." }],
    "\\b(am|is|are)\\s+(fully\\s+|completely\\s+|totally\\s+)?agree\\b",
  ),
  mist(
    "grammar-since-long",
    "grammar",
    "Tense — duration",
    "I am knowing her from my childhood.",
    "I've known her since my childhood.",
    "State verbs such as know, like, want and understand are not used in continuous forms.",
    "'know', 'like', 'want', 'understand' — এই রকম অবস্থা-বাচক ক্রিয়া continuous-এ বসে না।",
    "very-common",
    [{ wrong: "I am understanding now.", right: "I understand now." }],
    "\\b(am|is|are)\\s+(knowing|understanding|wanting|liking|believing|remembering)\\b",
  ),
  mist(
    "grammar-if-will",
    "grammar",
    "Conditionals",
    "If technology will improve, life will be easier.",
    "If technology improves, life will be easier.",
    "After 'if' in a real conditional, use the present simple — not 'will'.",
    "'if' এর পরে will বসে না; present simple বসে।",
    "common",
    [{ wrong: "If I will get time, I will call you.", right: "If I get time, I'll call you." }],
    "\\bif\\s+[^.]{0,25}\\bwill\\b",
  ),
  mist(
    "grammar-could-able",
    "grammar",
    "Modals",
    "I can able to speak English.",
    "I can speak English. / I'm able to speak English.",
    "Use 'can' or 'be able to', never both together.",
    "'can' এবং 'be able to' — দুটো একসঙ্গে ব্যবহার করা যায় না।",
    "common",
    [{ wrong: "I will can do it.", right: "I'll be able to do it." }],
    "\\b(can|could|will)\\s+able to\\b",
  ),

  /* ------------------------------------------------------------------ */
  /* Vocabulary                                                          */
  /* ------------------------------------------------------------------ */
  mist(
    "vocab-very-good-repeated",
    "vocabulary",
    "Repetition of 'good'",
    "It was good. The food was good. The people were good.",
    "It was a great evening — the food was excellent and the people were really welcoming.",
    "Choosing precise adjectives shows vocabulary range; 'good' repeated shows the opposite.",
    "একই 'good' বারবার না বলে 'excellent, welcoming, worth visiting' — নির্দিষ্ট শব্দ ব্যবহার করুন।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "vocab-nice-thing",
    "vocabulary",
    "Vague nouns",
    "It is a very nice thing for the people.",
    "It's genuinely useful for people in my area.",
    "'Thing' + 'nice' says almost nothing. Name the benefit instead.",
    "'thing' শব্দটি প্রায় কিছুই বোঝায় না — বরং উপকারটা কী, সেটি বলুন।",
    "very-common",
    undefined,
    "\\bnice thing\\b",
  ),
  mist(
    "vocab-doing-great",
    "vocabulary",
    "Overgeneralised phrases",
    "My hometown is doing great now.",
    "My hometown has grown quite fast in the last few years.",
    "Vague praise sounds memorised; specific observation sounds fluent.",
    "প্রশংসা করতে গিয়ে অস্পষ্ট না থাকুন — কী পরিবর্তন হয়েছে, তা বলুন।",
    "common",
    undefined,
    "\\bdoing (great|good|very good)\\b",
  ),
  mist(
    "vocab-more-better-word",
    "vocabulary",
    "Fillers as content",
    "It was a very very nice experience, totally wonderful, absolutely amazing.",
    "It was memorable — mainly because the whole family was there.",
    "Stacking intensifiers replaces meaning. Give one reason instead.",
    "একসঙ্গে অনেক বিশেষণ দিলে অর্থ কমে যায়; একটি কারণ বললে উত্তর শক্তিশালী হয়।",
    "common",
    undefined,
    "\\b(very very|totally wonderful|absolutely amazing)\\b",
  ),
  mist(
    "vocab-hard-vocabulary",
    "vocabulary",
    "Unnatural vocabulary",
    "I want to ameliorate my speaking proficiency for the purpose of obtaining a lucrative occupation.",
    "I want to improve my speaking so I can get a better job.",
    "Very formal words used without control sound unnatural. Clear, natural English scores better at Band 6–6.5.",
    "কঠিন শব্দ ব্যবহার করলেই নম্বর বাড়ে না — স্বাভাবিক ও নির্ভুল ব্যবহারই বড় কথা।",
    "common",
    undefined,
    "\\b(ameliorate|ubiquitous|plethora|myriad|endeavour to|in order to obtain)\\b",
  ),
  mist(
    "vocab-look-after-word",
    "vocabulary",
    "Phrasal verbs",
    "I take care of my little sister and I take care also of my studies.",
    "I look after my little sister and I also keep up with my studies.",
    "Repeating one phrase shows a narrow range; natural alternatives exist.",
    "একই phrase বারবার না দিয়ে 'look after', 'keep up with' — এভাবে বদলান।",
    "occasional",
    undefined,
    undefined,
  ),
  mist(
    "vocab-uptodate",
    "vocabulary",
    "Collocation",
    "I am always update with the news.",
    "I keep up with the news.",
    "'Keep up with' is the natural collocation; 'update' is a noun or a verb with a different use.",
    "'keep up with the news' — এটাই স্বাভাবিক ব্যবহার।",
    "common",
    undefined,
    "\\b(am|is|are)\\s+update\\s+with\\b",
  ),
  mist(
    "vocab-tension",
    "vocabulary",
    "False friend",
    "I had too much tension before the exam.",
    "I was really stressed before the exam.",
    "'Tension' describes strained relations; personal pressure is 'stress' or 'nerves'.",
    "ব্যক্তিগত চাপ বোঝাতে 'stress' বা 'nervous' বলুন; 'tension' সাধারণত সম্পর্কের টানাপোড়েনে ব্যবহৃত হয়।",
    "very-common",
    [{ wrong: "I was in tension.", right: "I was stressed / nervous." }],
    "\\b(in|too much|full of)\\s+tension\\b",
  ),
  mist(
    "vocab-opportunity-chance",
    "vocabulary",
    "Word choice",
    "My parents gave me many opportunities to study but I missed the opportunities.",
    "My parents gave me every chance to study, but I wasted the opportunity.",
    "Repeating a long noun makes the answer flat. Short synonyms keep the rhythm alive.",
    "একই শব্দ দুইবার না দিয়ে 'chance', 'opportunity' — পাল্টে ব্যবহার করুন।",
    "occasional",
    undefined,
    undefined,
  ),
  mist(
    "vocab-really-like",
    "vocabulary",
    "Overused intensifier",
    "I really like it very much, I really much enjoy it.",
    "I really enjoy it — I go almost every weekend.",
    "'Really / very much' cannot cover for a missing reason. Add a concrete detail.",
    "জোর দিয়ে বলা নয়, কারণ বলা জরুরি: 'I go almost every weekend.'",
    "very-common",
    undefined,
    "\\breally like it very much\\b",
  ),
  mist(
    "vocab-facilities",
    "vocabulary",
    "Overgeneralisation",
    "Our area has many facilities.",
    "Our area has good transport and a couple of decent schools.",
    "'Facilities' is vague. Name the things that exist.",
    "'facilities' বললে কী আছে বোঝা যায় না — নাম বলে দিন।",
    "common",
    undefined,
    "\\bmany facilities\\b",
  ),
  mist(
    "vocab-give-exam",
    "vocabulary",
    "Indian-English collocation",
    "I gave the exam last year and I got good marks.",
    "I took the exam last year and I got good marks.",
    "English says 'take / sit an exam' (and 'pass' or 'fail' it).",
    "'পরীক্ষা দেওয়া' বোঝাতে 'take an exam' ব্যবহার করুন — 'give' নয়।",
    "common",
    [{ wrong: "I gave IELTS twice.", right: "I took IELTS twice." }],
    "\\b(give|gave|giving)\\s+(the\\s+)?(exam|test|IELTS)\\b",
  ),

  /* ------------------------------------------------------------------ */
  /* Pronunciation (intelligibility, not accent)                         */
  /* ------------------------------------------------------------------ */
  mist(
    "pron-final-consonants",
    "pronunciation",
    "Final consonants",
    "I go to the marke_every morning.",
    "I go to the market every morning.",
    "Bangla speakers often drop final consonants. Missing sounds change words and cost intelligibility.",
    "শব্দের শেষ ব্যঞ্জন উচ্চারণে দুর্বল হলে শব্দ বদলে যায় — 'mar-ket' এর শেষ 't' স্পষ্ট করুন।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "pron-ed-endings",
    "pronunciation",
    "Regular past -ed",
    "I work_ed /ˈwɜːkɛd/ in a shop last year.",
    "I worked /ˈwɜːkt/ in a shop last year.",
    "The -ed ending has three sounds: /t/, /d/ and /ɪd/ — it is not always a separate syllable.",
    "-ed তিন রকম শোনায়: worked = 'workt' (/t/), played = 'playd' (/d/), wanted = 'wanted' (/ɪd/)। অতিরিক্ত 'এড' যোগ করবেন না।",
    "very-common",
    [{ wrong: "asked as /ˈɑːskɛd/", right: "asked as /ˈɑːskt/" }],
    undefined,
  ),
  mist(
    "pron-plural-s",
    "pronunciation",
    "Plural endings",
    "There were many student_ in the hall.",
    "There were many students in the hall.",
    "Plural -s is either /s/, /z/ or /ɪz/ and must be audible, especially before a vowel.",
    "students = /ˈstjuːdənts/ — শেষের 's' শুনতে পাওয়া জরুরি।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "pron-v-w",
    "pronunciation",
    "Consonants — v / w",
    "I have a very good wue of the walleys.",
    "I have a very good view of the valleys.",
    "/v/ uses the top teeth on the bottom lip. Without that contact 'very' becomes 'wery'.",
    "/v/ উচ্চারণে দাঁত ও ঠোঁটের স্পর্শ লাগে; বাংলায় অনেক সময় এটা /w/ হয়ে যায়।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "pron-s-sh",
    "pronunciation",
    "Consonants — s / ʃ",
    "In my শchool we study শcience.",
    "In my school we study science.",
    "'School' and 'science' begin with /s/, not /ʃ/. Bangla 'শ' pulls learners towards the wrong sound.",
    "'school', 'science'-এ শুরুতে /s/ — 'শ' নয়।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "pron-j-z",
    "pronunciation",
    "Consonants — j / z / dʒ",
    "My job is in a zeneral office.",
    "My job is in a general office.",
    "'General' starts with /dʒ/ as in 'job', not /z/.",
    "/dʒ/ ধ্বনি বাংলায় নেই — 'general'-এ 'job'-এর মতো শুরু হয়।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "pron-word-stress",
    "pronunciation",
    "Word stress",
    "I am studying ecoNOmics at univerSIty.",
    "I am studying ecoNOMics at a uniVERSity.",
    "Wrong word stress makes a correct word hard to follow.",
    "university = uni-VER-si-ty; economics = e-co-NOM-ics। শব্দের জোর ঠিক জায়গায় দিন।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "pron-chunking",
    "pronunciation",
    "Chunking and pauses",
    "Iwenttothecitywithmymotherandweboughtalotofthingsandthenwereturnedhome.",
    "I went to the city with my mother / and we bought a lot of things / and then we came home.",
    "Speaking in chunks with short pauses is easier to follow than one long stream.",
    "বাক্যকে ছোট ছোট অংশে ভাগ করে বলুন — ধীরে কিন্তু স্বাভাবিক শোনাবে।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "pron-intonation-flat",
    "pronunciation",
    "Intonation",
    "I like it. I like it? (same flat tone)",
    "I like it ↘. Do you like it ↗?",
    "Falling tone for statements, rising for yes/no questions. Flat delivery sounds memorised.",
    "বিবৃতিতে স্বর নিচে নামে, yes/no প্রশ্নে স্বর উপরে ওঠে।",
    "occasional",
    undefined,
    undefined,
  ),
  mist(
    "pron-th",
    "pronunciation",
    "Consonants — th",
    "I tink dis is de best option.",
    "I think this is the best option.",
    "/θ/ and /ð/ need the tongue lightly between the teeth. Replacing them with /t/ and /d/ hurts clarity.",
    "'th' উচ্চারণে জিভ দাঁতের ফাঁকে হালকা রাখুন — 't' বা 'd' নয়।",
    "very-common",
    undefined,
    undefined,
  ),

  /* ------------------------------------------------------------------ */
  /* Fluency                                                             */
  /* ------------------------------------------------------------------ */
  mist(
    "fluency-long-pause",
    "fluency",
    "Long pauses",
    "I think… (8 seconds silent) … it is good.",
    "I think… let me think for a second… it's mostly about the cost.",
    "Silence longer than a few seconds breaks the flow. A short thinking phrase keeps the answer alive.",
    "নীরব থাকার বদলে 'Let me think…' বলে সময় নিন — এতে fluency নষ্ট হয় না।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "fluency-bangla-filler",
    "fluency",
    "Bangla fillers",
    "Ah… hmm… mane… kemon jeno…",
    "Well… that's an interesting question.",
    "Bangla hesitation sounds do not help the examiner and are counted as pauses.",
    "বাংলা ভরপুরণ ('মানে', 'যেমন') নয় — ইংরেজি natural filler ব্যবহার করুন।",
    "very-common",
    undefined,
    "\\b(mane|kemon|ji|matlab)\\b",
  ),
  mist(
    "fluency-filler-overuse",
    "fluency",
    "Filler overuse",
    "Actually, actually I think actually it's actually good.",
    "Actually, I think it's genuinely useful.",
    "'Actually' used as a tic becomes a repetition problem and weakens meaning.",
    "একই filler বারবার ব্যবহার করলে repetition-এর দোষ হয়।",
    "very-common",
    undefined,
    "\\bactually\\b[^.]{0,15}\\bactually\\b",
  ),
  mist(
    "fluency-one-line-answers",
    "fluency",
    "Answer length",
    "Yes.",
    "Yes, I do — mainly because it saves me a lot of time in the morning.",
    "One-word answers cannot show range. Every Part 1 answer needs a reason or a detail.",
    "এক শব্দে উত্তর দিলে নম্বর পাওয়া যায় না — কারণ বা ছোট বিস্তারিত যোগ করুন।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "fluency-stops-to-self-correct",
    "fluency",
    "Self-correction",
    "I goed… no, I mean I go… no wait, I went there last year.",
    "I goed— sorry, I went there last year.",
    "One quick correction is fine; repeated restarts destroy fluency.",
    "একবার সংশোধন ঠিক আছে, কিন্তু বারবার শুরু করলে fluency কমে যায় — সংশোধন করে এগিয়ে যান।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "fluency-translation-pause",
    "fluency",
    "Bangla → English translation",
    "I will say a sentence in Bangla in my head, then translate… (long pause)",
    "Start with what you can already say, then add one detail.",
    "Translating whole sentences in your head is the biggest cause of long pauses.",
    "মাথায় পুরো বাক্য বাংলা বানিয়ে অনুবাদ করবেন না — যা পারেন তা দিয়েই শুরু করুন।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "fluency-repeating-question",
    "fluency",
    "Repeating the question",
    "Do I like music? Do I like music… hmm, do I like music?",
    "Do I like music? Yes, quite a lot actually.",
    "Repeating the question wastes the first five seconds of your answer.",
    "প্রশ্নটি হুবহু আবার বলবেন না — সরাসরি উত্তর দিয়ে শুরু করুন।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "fluency-rushing",
    "fluency",
    "Speed",
    "Talking so fast that the examiner asks you to repeat a word.",
    "Speaking at a steady pace, pausing briefly at the end of ideas.",
    "Speed is not fluency. Clear, steady pace with natural pauses sounds more confident.",
    "দ্রুত বলা মানে fluent নয় — স্পষ্ট ও স্থির গতিই ভালো।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "fluency-yes-no-no-reason",
    "fluency",
    "Answer structure",
    "No.",
    "Not really — I don't have much time for it these days, mainly because of work.",
    "In Part 1, a negative answer still needs a reason and a small detail.",
    "'No' বলে থেমে যাবেন না — কারণ ও ছোট বিস্তারিত দিন।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "fluency-abandoning-sentence",
    "fluency",
    "Sentence completion",
    "My favourite place is… no, actually… it's a place which… umm…",
    "My favourite place is a small café near my college — I go there once a week.",
    "Finishing an idea, even simply, matters more than perfect accuracy.",
    "বাক্য শেষ করুন — সহজ হলেও। অসম্পূর্ণ বাক্য fluency নষ্ট করে।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "fluency-memorised-tone",
    "fluency",
    "Memorised delivery",
    "Saying a pre-learned paragraph with flat, recited intonation.",
    "Answering with your own examples, varying sentence length naturally.",
    "Examiners hear memorised answers immediately — and they do not answer the question asked.",
    "মুখস্থ উত্তর পরীক্ষক সঙ্গে সঙ্গে ধরতে পারেন — নিজের উদাহরণ দিয়ে বলুন।",
    "occasional",
    undefined,
    undefined,
  ),

  /* ------------------------------------------------------------------ */
  /* Sentence structure                                                  */
  /* ------------------------------------------------------------------ */
  mist(
    "structure-two-verbs",
    "structure",
    "Two verbs in one clause",
    "I went to the market I bought some vegetables.",
    "I went to the market and bought some vegetables.",
    "Two full clauses need a connector or a full stop; otherwise the sentence collapses.",
    "দুইটি clause-এর মাঝে 'and', 'but', 'because' বা দাঁড়ি লাগবে।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "structure-and-and-and",
    "structure",
    "Overusing 'and'",
    "I woke up and I washed and I ate and I went to college and I studied.",
    "I woke up, had breakfast and went to college, where I studied until noon.",
    "Chaining everything with 'and' shows only simple sentences. Use subordinators for range.",
    "'and' দিয়ে সব জোড়া না লাগিয়ে 'where', 'after', 'because' ব্যবহার করুন।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "structure-run-on",
    "structure",
    "Run-on sentence",
    "I like my city because it is busy because there are many people because it is the capital.",
    "I like my city because it's busy — there are people everywhere, and after all it is the capital.",
    "Repeated 'because' creates a run-on and sounds mechanical.",
    "বারবার 'because' দিলে বাক্য ভেঙে পড়ে — 'so', 'that's why', 'which means' ভাগ করে ব্যবহার করুন।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "structure-no-relative",
    "structure",
    "Relative clauses missing",
    "I have a friend. My friend lives in Sylhet. My friend is a teacher.",
    "I have a friend who lives in Sylhet and teaches there.",
    "Relative clauses (who, which, where) combine short sentences and add range.",
    "'who / which / where' দিয়ে ছোট বাক্য জোড়া দিলে grammatical range বাড়ে।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "structure-perfect-too-many",
    "structure",
    "Overusing perfect tenses",
    "I have gone to Cox's Bazar in 2019 and I have enjoyed it.",
    "I went to Cox's Bazar in 2019 and I really enjoyed it.",
    "A finished past time (in 2019) requires the past simple, not the present perfect.",
    "নির্দিষ্ট অতীত সময় (in 2019, last year) থাকলে past simple বসে।",
    "common",
    undefined,
    "\\bhave\\s+(gone|been|visited|seen|done)\\b[^.]{0,30}\\b(in|last)\\s+(19|20)\\d{2}\\b",
  ),
  mist(
    "structure-incomplete-because",
    "structure",
    "Incomplete clauses",
    "Because I like the weather.",
    "I go there in winter because I like the weather.",
    "A sentence cannot start with 'because' alone in an exam answer — it leaves the main clause missing.",
    "'Because' দিয়ে শুরু করলে মূল বাক্যটি বাদ পড়ে যায় — সম্পূর্ণ ধারণা দিন।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "structure-no-contrast",
    "structure",
    "No contrast",
    "The village is quiet. The city is busy. (Two separate short sentences.)",
    "The village is quiet, whereas the city never really slows down.",
    "Contrast words (whereas, although, on the other hand) turn two facts into one developed idea.",
    "'whereas', 'although' দিয়ে তুলনা করলে উত্তর পরিণত শোনায়।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "structure-adverb-position",
    "structure",
    "Adverb position",
    "I like very much the food of my mother.",
    "I really like my mother's cooking.",
    "Adverbs rarely sit between the verb and its object in English.",
    "'very much' বাংলা ভাষার মতো ক্রিয়ার পরে বসানো যায় না — 'really like' বলুন।",
    "common",
    undefined,
    "\\b(like|enjoy|love)\\s+very much\\s+(the|my|this|that)\\b",
  ),
  mist(
    "structure-subject-drop",
    "structure",
    "Missing subject",
    "Is very important for students.",
    "It's very important for students.",
    "English needs an explicit subject; Bangla often drops it.",
    "বাংলায় কর্তা বাদ দেওয়া গেলেও ইংরেজিতে 'it' বা subject বাধ্যতামূলক।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "structure-double-negative",
    "structure",
    "Double negative",
    "I don't know nothing about it.",
    "I don't know anything about it.",
    "English allows only one negative in a clause.",
    "একটি clause-এ একবারই negative বসে — 'don't know anything'।",
    "common",
    undefined,
    "\\bdon'?t\\s+(know|have|want|see|like)\\s+nothing\\b",
  ),
  mist(
    "structure-gonna-plain",
    "structure",
    "Contractions in formal answer",
    "I am going to say that it is not possible for me to say that.",
    "Honestly, it's hard to say — but I'd probably choose the first one.",
    "Over-formal full forms sound stiff; natural spoken English uses contractions.",
    "কথ্য ইংরেজিতে contraction স্বাভাবিক: it's, I'd, that's।",
    "occasional",
    undefined,
    undefined,
  ),
  mist(
    "structure-topic-drift",
    "structure",
    "Unrelated development",
    "Question: about your hometown. Answer drifts into your exam results for one minute.",
    "Question: about your hometown. Answer: location, one change, one memory — all about the town.",
    "Development must stay on the question. Unrelated detail costs you on both content and coherence.",
    "উত্তর প্রশ্নের বিষয়েই থাকতে হবে — অপ্রাসঙ্গিক গল্প বললে নম্বর কমে।",
    "common",
    undefined,
    undefined,
  ),

  /* ------------------------------------------------------------------ */
  /* Word choice                                                         */
  /* ------------------------------------------------------------------ */
  mist(
    "choice-say-vs-tell",
    "word-choice",
    "say / tell",
    "He said me that he was busy.",
    "He told me that he was busy.",
    "'Tell' takes a person directly; 'say' needs 'to'. Tell someone, say something.",
    "tell + ব্যক্তি (tell me); say + বক্তব্য (say something to me)।",
    "very-common",
    [{ wrong: "She said to me that…", right: "She told me that…" }],
    "\\b(said|say)\\s+(me|him|her|us|them)\\b",
  ),
  mist(
    "choice-make-do",
    "word-choice",
    "make / do",
    "I need to make my homework and do a decision.",
    "I need to do my homework and make a decision.",
    "Fixed collocations: do homework, do research, make a decision, make progress.",
    "do homework, do research; make a decision, make progress — এগুলো নির্দিষ্ট জোড়া।",
    "common",
    [{ wrong: "I made a lot of mistakes in my study.", right: "I made a lot of mistakes in my studies." }],
    "\\b(make|made)\\s+(my\\s+)?homework\\b|\\b(do|did)\\s+a\\s+decision\\b",
  ),
  mist(
    "choice-borrow-lend",
    "word-choice",
    "borrow / lend",
    "Can you borrow me your book?",
    "Can you lend me your book?",
    "You borrow *from* someone; you lend *to* someone. The direction reverses.",
    "borrow = নেওয়া (from), lend = দেওয়া (to)।",
    "common",
    undefined,
    "\\bborrow\\s+(me|him|her|us|them)\\b",
  ),
  mist(
    "choice-learn-teach",
    "word-choice",
    "learn / teach",
    "My teacher learned me how to write.",
    "My teacher taught me how to write.",
    "You learn a subject; a teacher teaches you.",
    "'teach' = শেখানো, 'learn' = শেখা — কর্তা অনুযায়ী বদলায়।",
    "common",
    undefined,
    "\\b(learned|learnt)\\s+(me|him|her|us|them)\\b",
  ),
  mist(
    "choice-news-information",
    "word-choice",
    "Countable / uncountable",
    "I heard a news about it yesterday.",
    "I heard a piece of news about it yesterday.",
    "'News' is uncountable — you can say 'some news' or 'a piece of news'.",
    "'news' অগণনীয় — 'a news' হয় না, 'a piece of news' হয়।",
    "common",
    undefined,
    "\\ba\\s+(news|information|advice|furniture|work)\\b",
  ),
  mist(
    "choice-person-persons",
    "word-choice",
    "Plural forms",
    "There were five persons in the room.",
    "There were five people in the room.",
    "In everyday English the plural of 'person' is 'people'. 'Persons' is legal or official language.",
    "সাধারণ ইংরেজিতে plural = people; 'persons' শুধু আইনি বা দাপ্তরিক লেখায়।",
    "common",
    undefined,
    "\\b(persons|childrens|womens|mens|peoples)\\b",
  ),
  mist(
    "choice-book-reading",
    "word-choice",
    "Verb choice",
    "I am reading a book for improving my English.",
    "I'm reading a book to improve my English.",
    "Use 'to + verb' for purpose instead of 'for + -ing' when the purpose is an action.",
    "উদ্দেশ্য বোঝাতে 'to + verb' সহজ ও স্বাভাবিক।",
    "common",
    undefined,
    "\\bfor\\s+(improving|learning|getting|becoming|buying)\\b",
  ),
  mist(
    "choice-very-much-like",
    "word-choice",
    "Placement",
    "I very much like to travel.",
    "I really enjoy travelling.",
    "In speech, 'really' is far more natural before 'like / enjoy'.",
    "'very much' কথ্য ইংরেজিতে ভারী শোনায় — 'really enjoy' বলুন।",
    "common",
    undefined,
    "\\bvery much like\\b",
  ),
  mist(
    "choice-boss-owner",
    "word-choice",
    "Imprecise nouns",
    "My office boss is very good.",
    "My manager at work is really supportive.",
    "Name the relationship precisely: manager, colleague, supervisor, team leader.",
    "সম্পর্ক নির্দিষ্ট করে বলুন: manager, colleague, supervisor।",
    "occasional",
    undefined,
    undefined,
  ),
  mist(
    "choice-countryside-village",
    "word-choice",
    "Region vocabulary",
    "I grew up in a countryside.",
    "I grew up in the countryside / in a village.",
    "'Countryside' is uncountable in this sense; 'a village' is countable.",
    "'countryside' এখানে uncountable — 'a countryside' হয় না।",
    "common",
    undefined,
    "\\ba countryside\\b",
  ),
  mist(
    "choice-doctor-treatment",
    "word-choice",
    "Health vocabulary",
    "The doctor gave me a treatment and I became fine.",
    "The doctor treated me and I recovered.",
    "Say what happened in plain verbs: treated, recovered, prescribed, referred.",
    "চিকিৎসা বোঝাতে 'treated me', সুস্থ হতে 'recovered' — সরল ক্রিয়া ভালো।",
    "occasional",
    undefined,
    undefined,
  ),
  mist(
    "choice-too-enough",
    "word-choice",
    "too / very / enough",
    "The bus was too crowded, but it was fine.",
    "The bus was very crowded, but it was fine.",
    "'Too' always carries a problem; if there is no problem, use 'very' or 'really'.",
    "'too' মানে সমস্যা বোঝায় — সমস্যা না থাকলে 'very' বা 'really' বলুন।",
    "common",
    [{ wrong: "The exam was too easy and I enjoyed it.", right: "The exam was quite easy and I enjoyed it." }],
    undefined,
  ),

  /* ------------------------------------------------------------------ */
  /* Direct translation from Bangla                                      */
  /* ------------------------------------------------------------------ */
  mist(
    "translation-give-exam",
    "translation",
    "Bangla → English verb",
    "I gave my exam yesterday.",
    "I took my exam yesterday.",
    "'পরীক্ষা দেওয়া' translates as 'take / sit an exam'.",
    "'পরীক্ষা দেওয়া' = 'take an exam' — শব্দে শব্দে অনুবাদ করা যাবে না।",
    "very-common",
    undefined,
    "\\b(give|gave|giving)\\s+(my\\s+|the\\s+)?(exam|test|IELTS)\\b",
  ),
  mist(
    "translation-tension",
    "translation",
    "Bangla → English noun",
    "I had much tension before the interview.",
    "I was really nervous before the interview.",
    "'Tension' in English means strained relations, not personal stress.",
    "ব্যক্তিগত চাপে 'nervous / stressed' বলুন।",
    "very-common",
    undefined,
    "\\b(much|too much|full of)\\s+tension\\b",
  ),
  mist(
    "translation-full-family",
    "translation",
    "Bangla → English idiom",
    "My full family went there together.",
    "My whole family went there together.",
    "English says 'whole family' or 'the entire family'.",
    "'full family' নয় — 'whole family' বলুন।",
    "very-common",
    undefined,
    "\\bfull family\\b",
  ),
  mist(
    "translation-outside-food",
    "translation",
    "Bangla → English phrase",
    "We ate outside food last night.",
    "We ate out last night.",
    "'বাইরের খাবার' = eating out / takeaway, not 'outside food'.",
    "'বাইরের খাবার' = 'ate out' বা 'takeaway'।",
    "very-common",
    undefined,
    "\\boutside food\\b",
  ),
  mist(
    "translation-do-great",
    "translation",
    "Bangla → English verb",
    "I did a great job in the exam, I did a mistake in one question.",
    "I did well in the exam, though I made a mistake in one question.",
    "'Do a mistake' is a translation error — English uses 'make a mistake'.",
    "'ভুল করা' = 'make a mistake'; 'do a mistake' ভুল।",
    "very-common",
    undefined,
    "\\bdid\\s+a\\s+mistake\\b|\\bdo\\s+mistakes\\b",
  ),
  mist(
    "translation-know-vs-meet",
    "translation",
    "Bangla → English verb",
    "I know him for ten years.",
    "I've known him for ten years.",
    "'চেনা' communicates a state; states cannot be expressed with a finished present.",
    "'জানি / চিনি' বোঝাতে 'have known' বসে, 'know' একা নয়।",
    "common",
    undefined,
    "\\bknow\\b[^.]{0,20}\\bfor\\s+(two|three|five|ten|\\d+)\\s+year",
  ),
  mist(
    "translation-return-back",
    "translation",
    "Repetition in translation",
    "I returned back home and discussed about it with my parents.",
    "I came home and discussed it with my parents.",
    "'Return' already contains 'back'; 'discuss' needs no 'about'.",
    "'return back' — একই অর্থ দুইবার; 'discuss about' — preposition বাড়তি।",
    "common",
    [{ wrong: "Please repeat again.", right: "Please repeat that." }],
    "\\b(return(ed)? back|discuss(ed)? about|repeat again|revert back)\\b",
  ),
  mist(
    "translation-since-long-time",
    "translation",
    "Time expressions",
    "I am not going there since long time.",
    "I haven't been there for a long time.",
    "Bangla time expressions rarely map one-to-one; use 'for' + duration with a perfect tense.",
    "'since long time' নয় — 'for a long time' বসবে।",
    "very-common",
    undefined,
    "\\bsince\\s+(long|many|much)\\b",
  ),
  mist(
    "translation-good-in",
    "translation",
    "Adjective + preposition",
    "I am good in English but weak in maths.",
    "I'm good at English but weak at maths.",
    "The fixed pair is 'good at' and 'weak at'.",
    "'good at', 'weak at' — এটাই নির্দিষ্ট জোড়া।",
    "common",
    undefined,
    "\\b(good|weak|bad|strong)\\s+in\\s+(English|maths|math|science|studies)\\b",
  ),
  mist(
    "translation-hot-cold",
    "translation",
    "Weather vocabulary",
    "Today the weather is very hot hot, I am feeling so much heat.",
    "It's been really hot today — almost unbearable by the afternoon.",
    "Repeat words and heavy nouns sound unnatural; describe the effect instead.",
    "'very hot hot' নয় — 'really hot' এবং তার প্রভাব বর্ণনা করুন।",
    "common",
    undefined,
    "\\bhot hot\\b|\\bso much heat\\b",
  ),
  mist(
    "translation-climbing-tree",
    "translation",
    "Literal idioms",
    "We were climbing trees and eating the brain of the coconut.",
    "We used to climb trees and eat fresh coconut.",
    "'মাথা' as 'brain' is a literal translation; English uses 'coconut water' and 'flesh'.",
    "শব্দে-শব্দে অনুবাদ করলে অর্থ বিকৃত হয় — স্বাভাবিক ইংরেজি ব্যবহার করুন।",
    "occasional",
    undefined,
    undefined,
  ),
  mist(
    "translation-cousin-brother",
    "translation",
    "Family vocabulary",
    "My cousin brother lives with us.",
    "My cousin lives with us.",
    "English 'cousin' covers the Bangla distinctions of ভাই ও বোন.",
    "ইংরেজিতে 'cousin' শব্দটি ভাই-বোন দুটোর জন্যই চলে — 'cousin brother' নয়।",
    "very-common",
    undefined,
    "\\bcousin\\s+(brother|sister)\\b",
  ),

  /* ------------------------------------------------------------------ */
  /* Repetition                                                          */
  /* ------------------------------------------------------------------ */
  mist(
    "repetition-actually-open",
    "repetition",
    "Every answer starting the same way",
    "Actually I like it. Actually it's good. Actually I go there…",
    "I go there most weekends — it's become a habit.",
    "Starting every sentence with the same word is the clearest repetition signal in a test.",
    "প্রতিটি বাক্য 'Actually' দিয়ে শুরু করলে repetition ধরা পড়ে — কখনও সরাসরি শুরু করুন।",
    "very-common",
    undefined,
    "\\bactually\\b[^.]{0,30}\\bactually\\b",
  ),
  mist(
    "repetition-because",
    "repetition",
    "Overused connector",
    "I like it because it's near because my friend lives there because it's cheap.",
    "I like it because it's close by, and my friend lives just around the corner, so I never go alone.",
    "Repeating 'because' three times in one answer shows a limited connector range.",
    "'because' এর বদলে 'so', 'which means', 'that's why' ব্যবহার করুন।",
    "very-common",
    undefined,
    "\\bbecause\\b[^.]{0,20}\\bbecause\\b",
  ),
  mist(
    "repetition-and-then",
    "repetition",
    "Chained sequencing",
    "And then I woke up and then I ate and then I went out and then…",
    "I woke up early, had breakfast quickly, and was out of the house by eight.",
    "Use varied sequencing: after that, once, by the time, eventually.",
    "'and then' বারবার না দিয়ে 'after that', 'eventually', 'by the time' ব্যবহার করুন।",
    "very-common",
    undefined,
    "\\bthen\\b[^.]{0,15}\\bthen\\b",
  ),
  mist(
    "repetition-very",
    "repetition",
    "Intensifier repetition",
    "It was very very good and very nice and very much enjoyable.",
    "It was a genuinely enjoyable evening — much better than I expected.",
    "One strong phrase beats four weak intensifiers.",
    "একটি শক্তিশালী বাক্যাংশ অনেক 'very'-এর চেয়ে ভালো।",
    "very-common",
    undefined,
    "\\bvery\\b[^.]{0,12}\\bvery\\b",
  ),
  mist(
    "repetition-good",
    "repetition",
    "Adjective repetition",
    "It is good. The teacher is good. The class is good. Everything is good.",
    "The teacher explains things clearly, so even the difficult classes feel manageable.",
    "Repeating one adjective across four sentences limits lexical resource.",
    "একই বিশেষণ বারবার নয় — 'clear', 'useful', 'well-organised' ভাগ করে ব্যবহার করুন।",
    "very-common",
    undefined,
    undefined,
  ),
  mist(
    "repetition-i-think",
    "repetition",
    "Opinion marker repetition",
    "I think it is good. I think people like it. I think it will grow.",
    "I think it's good — people clearly like it, and I'd expect it to grow.",
    "One opinion marker at the start is enough; then let the reasons carry the answer.",
    "প্রথম বাক্যে 'I think' বলুন, তারপর কারণ দিন — বারবার নয়।",
    "common",
    undefined,
    "\\bi think\\b[^.]{0,20}\\bi think\\b",
  ),
  mist(
    "repetition-like",
    "repetition",
    "Verb repetition",
    "I like it. I like the food. I like the people. I like everything.",
    "I like it for the food, but what keeps me going back is the people.",
    "Varying the verb (enjoy, prefer, appreciate, keep going back) adds lexical range.",
    "'like' এর বিকল্প: enjoy, prefer, appreciate — ব্যবহারে বৈচিত্র্য আনুন।",
    "very-common",
    undefined,
    "\\bi like\\b[^.]{0,20}\\bi like\\b",
  ),
  mist(
    "repetition-my-country",
    "repetition",
    "Phrase repetition",
    "In my country, in my country, the people of my country…",
    "Here in Bangladesh… / Where I live… / In most Bangladeshi cities…",
    "Repeating a long phrase wastes time and sounds mechanical.",
    "'In my country' বারবার না দিয়ে 'Here in Bangladesh', 'Where I live' ভাগ করে বলুন।",
    "common",
    undefined,
    "\\bmy country\\b[^.]{0,25}\\bmy country\\b",
  ),
  mist(
    "repetition-question-words",
    "repetition",
    "Copying the question",
    "Do people in your country like music? Do people in my country like music… yes…",
    "Yes, most people I know listen to music daily — it's part of the commute.",
    "Copying the question into the answer wastes time and shows no independent phrasing.",
    "প্রশ্ন হুবহু দোহড়াবেন না — সরাসরি উত্তর শুরু করুন।",
    "common",
    undefined,
    undefined,
  ),
  mist(
    "repetition-filler-words",
    "repetition",
    "Filler repetition",
    "You know, like, you know, like, I mean…",
    "Well, the main thing is…",
    "Filler words repeated become noise. Use one thoughtful phrase and then continue.",
    "একই filler বারবার নয় — একবার 'Well…' বলে এগিয়ে যান।",
    "common",
    undefined,
    "\\b(you know|i mean|like)\\b[^.]{0,12}\\b\\1\\b",
  ),
];
